### ISSUE TITLE
Drop support for Silverlight

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#100]
With Microsoft's support for Silverlight declining and just general use for new work close to non-existent we need to consider whether the effort to continue keeping it supported in Castle Core is worthwhile. Many of us have wanted to drop it completely (both v4 and v5, v3 support was dropped long ago).

Microsoft has just announced that Microsoft Edge will not run any sort of built-in Silverlight like they are doing with Adobe Flash:

> Support for ActiveX has been discontinued in Microsoft Edge, and that includes removing support for Silverlight.  The reasons for this have been discussed in previous blogs and include the emergence of viable and secure media solutions based on HTML5 extensions.  Microsoft continues to support Silverlight, and Silverlight out-of-browser apps can continue to use it.  Silverlight will also continue to be supported in Internet Explorer 11, so sites continue to have Silverlight options in Windows 10.
> (http://blogs.windows.com/msedgedev/2015/07/02/moving-to-html5-premium-media/)

> Microsoft Edge will support native PDF rendering and Adobe Flash as built-in features rather than external add-ons.
> (http://blogs.windows.com/msedgedev/2015/05/06/a-break-from-the-past-part-2-saying-goodbye-to-activex-vbscript-attachevent/)

This issue is a discussion thread to get people's opinions on dropping all Silverlight support, we want to make an informed decision, a decision hasn't been made yet so we want to hear feedback as we prepare for the next major release.

/cc (lets start with those listed as organisation members of the mocking frameworks)
Moq: @kalebpederson @kzu @tkellogg
FakeItEasy: @adamralph @blairconrad @patrik-hagne @philippdolder
NSubstitute: @AnthonyEgerton @dtchepak

**Comment by kkozmic** [comment]
I'm all for dropping it

**Comment by jonorossi** [comment]
@kkozmic don't worry, I don't think anyone wasn't already aware :wink:

**Comment by blairconrad** [comment]
@jonorossi, thanks for thinking about us mocking frameworks.
You're within your rights to drop whatever you want whenever you want, and I really appreciate that you thought of us.
One thing to remember is that even if we want to keep using the Silverlight Castle.Core libraries, there's always version 3.3.3 to fall back on (and _our_ clients could always fall back on whatever version we last offered SL support in, assuming we remove it).

Unfortunately, I don't have much more to add than that. I've never used Silverlight, and I tend to be isolated from platform considerations, as my Day Job keeps me working on legacy platforms (we're considering supporting .NET 4.5 sometime in the near future).

I don't know whether many people care about the FakeItEasy for SL5 (we dropped SL4 in January 2014 (FakeItEasy/FakeItEasy#218).
We _do_ export a win8 FakeItEasy library which is actually a copy of the SL5 version. I think that gets a little more use, but I can't say for sure that it's that popular.

Okay. Now to sit back and let people who understand things comment!

**Comment by jonorossi** [comment]
@blairconrad no problem, today mocking frameworks are really the driver for a lot of DP's usage and wide platform use cases. I too have never built anything with Silverlight, and know few people that have. I get that we can drop support when we want, I just want to consult you guys so we don't piss off project leaders.

We are working on .NET Core support at the moment for vNext, which should hopefully provide support for UWP apps out of the box which I think will have more demand that Windows 8 Store apps.

**Comment by kzu** [comment]
+1

Those who care can stay on older mocking library versions, just like they
are staying on old platforms ;)

**Comment by adamralph** [comment]
:+1: from me. I don't mind dropping SL support in newer versions of FakeItEasy.

**Comment by blairconrad** [comment]
(And the upcoming 2.0 release seems like as good a time as any!)

**Comment by adamralph** [comment]
Indeed!

**Comment by dtchepak** [comment]
Hi @jonorossi, thanks for the ping. NSubstitute doesn't support SL, so definitely no objections here. :)

**Comment by blairconrad** [comment]
An update, in case it matters: FakeItEasy/FakeItEasy#507 has been closed, removing Silverlight support from the FakeItEasy 2.0 branch.

**Comment by blairconrad** [comment]
@jonorossi, for what it's worth, I think we have a response from members of the big three mocking frameworks. Is this sufficient for go-ahead, or does it just open the door for further discussion?

**Comment by jonorossi** [comment]
@blairconrad yes the discussion is done, I assigned it to myself in September because I wanted to make sure we finished the rest of the conditional compilation for .NET Core so we could easily see what we had done for Silverlight. Now that most of .NET Core is done, I've just done the work to remove Silverlight support completely in the `netcore` branch.

**Comment by blairconrad** [comment]
@jonorossi, oh, cool. I'd've done the excising to try to save you some work, but it sounds like it was pretty quick. Thanks!
