### ISSUE TITLE
Cannot create proxy for interface with custom attribute having an enum array parameter

### ISSUE THREAD

**Issue by csharper2010** [castleproject/Core#104]
SetUp : System.InvalidCastException : Mindestens ein Element im Quellarray konnte nicht in den Zielarraytyp umgewandelt werden.
   bei System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   bei System.Array.CopyTo(Array array, Int32 index)
   bei Castle.DynamicProxy.Internal.AttributeUtil.ReadAttributeValue(CustomAttributeTypedArgument argument) in AttributeUtil.cs: line 97.
   bei Castle.DynamicProxy.Internal.AttributeUtil.GetCtorArguments(IList`1 constructorArguments) in AttributeUtil.cs: line 81.
   bei Castle.DynamicProxy.Internal.AttributeUtil.CreateBuilder(CustomAttributeData attribute) in AttributeUtil.cs: line 67.
   bei ...

**Comment by kkozmic** [comment]
Hey, thanks for the PR.

There's some indention issue in some places. Also, could you make sure (add tests) it works for all enums, not just `int` based?

cheers
Krzysztof

**Comment by jonorossi** [comment]
The pull request #105 was merged last year, this issue just didn't get closed at the time.
