### ISSUE TITLE
Generic method with differently named generic arguments to parent throws KeyNotFoundException

### ISSUE THREAD

**Issue by HelloKitty** [castleproject/Core#106]
Issue: Throws KeyNotFoundException in https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Generators/Emitters/AbstractTypeEmitter.cs at method public Type[] GetGenericArgumentsFor(MethodInfo genericMethod)

Conditions: When Type name of generic type doesn't match the name of the Type in an interface.

Workaround: Change any generic Type names to match the name on the source interface.

This happens in Mono and .Net. If a generic method's generic Type name mismatches with its implemented name then this throws in Moq.

Original issues incorrectly posted on Moq's GitHub: [here](https://github.com/Moq/moq4/issues/193)

**Comment by kkozmic-seek** [comment]
Hey @HelloKitty 

Is this still an issue or was that MOQ specific?

**Comment by kkozmic** [comment]
Also, if it's not and it's still an issue, can you elaborate on when the issue occurs. Posting a failing test would help.

**Comment by jonorossi** [comment]
Based on other non-Castle GitHub issues others have linked here the problem is as the test below highlights, the interface and implementation generic arguments must have the same name otherwise DynamicProxy breaks:

```csharp
public interface ITest
{
	void Hi<T>();
}
public class Test : ITest
{
	public void Hi<T2>()
	{
	}
}

[Test]
public void GenericMethodDifferentlyNamedGenericArguments()
{
	generator.CreateClassProxy(typeof(Test), new[] { typeof(ITest) }, new DoNothingInterceptor());
}
```

Failure:
```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
TearDown : System.NotSupportedException : Type 'Castle.Proxies.TestProxy' was not completed.
```

**Comment by jonorossi** [comment]
Since this is a long standing defect and has a workaround, I'm removing it from the v4.0 milestone.
