### ISSUE TITLE
.NET Core - sort out NUnit shim over xUnit.net

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#127]
1. Does the NUnitLite that recently shipped provide what we need for .NET Core?
1. Are we staying with NUnit or moving the whole project to xUnit.net?
1. If we are staying with NUnit we don't need the shim anymore, if we are going to move to xUnit.net, then maybe the shim is a good transition tool to reduce code churn.

**Comment by jeremymeng** [comment]
RE: NUnitLite v3

Currently there's no VS integrated runner or Dnx runner support.  A Dnx console project must be created to run the tests.  See [this for an example](https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis.Tests/Program.cs). Unfortunately it doesn't seem to support `-nologo`, `-noshadow`, or `-xml` options.

**Comment by jonorossi** [comment]
The NUnit team have an issue logged (https://github.com/nunit/nunit/issues/927) to add a DNX runner, however I suspect with the state of flux of DNX/CLI especially around commands they'll be waiting for it to stabilise.

I'm happy to leave this issue to later (even post-4.0 if needed) since the shim I made is working pretty well for now. @jeremymeng do you see any problem with us releasing 4.0 without this resolved?

**Comment by jeremymeng** [comment]
> do you see any problem with us releasing 4.0 without this resolved?

No. It should be good as long as there are test coverages.

**Comment by jonorossi** [comment]
Looks like many people are making good use of the new `dotnet-test-nunit` package, and it should be [updated to RTM bits within a day](https://github.com/nunit/nunit/issues/575#issuecomment-229175578).

http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/

**Comment by jeremymeng** [comment]
@jonorossi switching to `dotnet-test-nunit` is super easy. It just worked!  Upgrading desktop projects to NUnit v3 is a little more involved.  Let me know if you want to change back to NUnit.  I have a commit https://github.com/jeremymeng/Core/commit/e08847ad8d8f5601cf42374c76f20cde3cedbe69 and could submit a PR. I haven't removed the xunit shim.

**Comment by jeremymeng** [comment]
Haven't tested on Mono yet.

**Comment by jeremymeng** [comment]
Tests run and pass on Mono.  Only difference is that now the following three `[Explicit]` tests are marked as ignored by NUnit3.
```
27) Explicit : Castle.Core.Tests.Resources.UncResourceFactoryTestCase.CreateRelative
28) Explicit : Castle.Core.Tests.Resources.UncResourceFactoryTestCase.CreateWithAbsolutePath
29) Explicit : Castle.Core.Tests.Resources.UncResourceFactoryTestCase.NonExistingResource
```

**Comment by jeremymeng** [comment]
@jonorossi one question about the teamcity Mono build: is there a setting somewhere to set the WarningLevel to 2?  In my local build the default is 4 which caused some warnings reported as errors.  I had to pass `/p:WarningLevel=2` to xbuild.

**Comment by jonorossi** [comment]
TeamCity is just calling `xbuild /p:Configuration=NET45-Release /t:RunAllTests buildscripts/Build.proj`, maybe a difference in Mono version. I need to upgrade Mono anyway.

The build output for the Mono build on the TeamCity server shows this (CS1591 is missing XML comment):
```
/usr/lib/mono/4.5/mcs.exe ... /warnaserror+ ... /nowarn:1591 ... /warn:2
```

**Comment by jonorossi** [comment]
@jeremymeng could you please submit a PR to upgrade NUnit and change to using their .NET CLI runner, just leave the conditional code for now.

**Comment by jeremymeng** [comment]
@jonorossi PR submitted.

**Comment by jonorossi** [comment]
#202 has been merged.

TeamCity doesn't seem to support the NUnit test result XML files, I'll upgrade TeamCity which should hopefully resolve the problem.

**Comment by jeremymeng** [comment]
@jonorossi Awesome work!  I think nunit3 console runner has an option to output legacy nunit2 style XML format, if that helps.

**Comment by jeremymeng** [comment]
There's even an option for TeamCity, though I don't know what messages are those.

```
     --teamcity             Turns on use of TeamCity service messages.
```

**Comment by jonorossi** [comment]
> I think nunit3 console runner has an option to output legacy nunit2 style XML format, if that helps.

Yep, `--result:filename;format=nunit2` just looking at it at the moment.

> There's even an option for TeamCity, though I don't know what messages are those

I assume it'll be using the standard TeamCity testStarted/testFinished service messages. We are currently using the importData service message. I read just before that TeamCity or NUnit 3 are meant to auto-detect each other, however that might be in a newer TeamCity.

**Comment by jonorossi** [comment]
Found out you need the `NUnit.Extension.TeamCityEventListener` package files for auto-detection.

**Comment by jeremymeng** [comment]
> I read just before that TeamCity or NUnit 3 are meant to auto-detect each other, however that might be in a newer TeamCity.

It looks so from this [blog post](https://blog.jetbrains.com/teamcity/2015/11/teamcity-and-nunit-3/).  Maybe it only works when being run as a TeamCity step?

**Comment by jonorossi** [comment]
I got the .NET Framework builds working last night with the NUnit's TeamCity addin, however because the dotnet-test-nunit runner is a completely different runner (it doesn't use the same test engine) it doesn't support addins or output formatters so I can only get a nunit3 formatted file out of it. No idea if TeamCity can even read these files yet, will look into it.

**Comment by jeremymeng** [comment]
@rprouse any ideas about TeamCity's support of reading nunit3 format result file?

**Comment by rprouse** [comment]
@jeremymeng sorry, I don't know the status of TeamCity supporting the NUnit3 format. @NikolayPianikov can you help?

At work, we use ReportUnit to translate the nunit3 result format to HTML. An option?

**Comment by jonorossi** [comment]
> any ideas about TeamCity's support of reading nunit3 format result file?

I upgraded to TeamCity 9.1.7 last night not longer after I last posted, the nunit3 format didn't work, no tests appeared in TeamCity. The TeamCity docs (https://confluence.jetbrains.com/display/TCD9/NUnit+Support) state support for NUnit 3 but no mention if they achieve that using the nunit2 format which dotnet-test-nunit can't provide.

**Comment by rprouse** [comment]
@jonorossi it sounds like you are running into the issue that TeamCity added custom code to the NUnit console to emit events that TeamCity subscribes to. In retrospect, we felt it might have been a mistake to allow custom code for one CI system when all the others do not need it. All of the other CI systems run the tests, emit console output to track progress, then either pass/fail based on the return code of NUnit and/or parse the test results.

We felt that it was a slippery slope allowing 3rd Party products to start adding code to NUnit, so we are looking at creating more of a plugin model going forward. We have an initial TeamCity plugin/extension now for the console runner, but we don't have one for .NET Core. I am willing to work with TeamCity on that, but I'm not going to write it myself :smile: 

In the meantime, I would suggest modifying your build to execute `dotnet test` directly rather than rely on the NUnit Addin for TeamCity. That is how the NUnit team does it on Travis and AppVeyor for all of our projects.

**Comment by jonorossi** [comment]
@rprouse thanks for the details, however we've never used JetBrains's NUnit addin or the NUnit --teamcity option, I too don't like developer tools having to implement specific logic for each CI product. We've always used the TeamCity XML Report Processing build feature and just point it at the testresults.xml file (or publish the results with a single TC service message), which is why I had to add the `;format=nunit2` for the .NET Framework builds for the output.

We do run `dotnet test` directly, the problem we've got at the moment is that TeamCity's XML Report Processing feature doesn't seem to understand the NUnit3 XML file and since `dotnet-test-nunit` doesn't use the normal engine doesn't support the `nunit-v2-result-writer.dll` addin.

**Comment by jonorossi** [comment]
@rprouse I should also add that this issue has all sorts of strange comments about using different things to my previous comment, I've just been throwing everything at the wall to see what sticks to get things to work, and tried the NUnit TeamCity addin at one point before finding `;format=nunit2`.

**Comment by rprouse** [comment]
@jonorossi thanks for the update. Maybe I should support the nunit2 format in .NET Core. I kind of wish we didn't add that support to NUnit 3 though. A couple years in and all of the tool vendors are still relying on the v2 support :frowning:

**Comment by jonorossi** [comment]
@rprouse I was surprised TeamCity didn't understand the format too, there were no errors just no tests. Looking at the source code of the XML Reporting Plugin it definitely doesn't support the new format. I couldn't find an issue in their issue tracker, however I didn't look through all the pages.

* https://confluence.jetbrains.com/display/TCD9/XML+Report+Processing
* https://confluence.jetbrains.com/display/TW/XML+Test+Reporting
* http://svn.jetbrains.org/teamcity/plugins/xml-tests-reporting/trunk/agent/src/jetbrains/buildServer/xmlReportPlugin/parsers/nUnit/NUnitXmlReportParser.java

I'd be nice if you added support into the .NET Core runner, otherwise we'll just continue with pass/fail overall reporting for .NET Core. Actually, I could probably throw something together in PowerShell pretty quickly to get what we need. We should then get an issue logged to give JB a push to actually implement proper support since they say they support it, then you guys just point everyone to the TC issue to upvote.

Oh, and it looks like your wish is granted with respect to their NUnit plugins, sounds like they are going to depreciate them: https://youtrack.jetbrains.com/issue/TW-43784.

**Comment by jonorossi** [comment]
@rprouse @jeremymeng I've implemented manual publishing of the unit test results for .NET Core from the nunit3 format to TeamCity in b6e3993f6974b80af76033eeacaa905afa3ba620, it'll do for us until JetBrains implements support for the nunit3 format.

**Comment by jonorossi** [comment]
I've removed the shim in #204 so we are all done here.
