### ISSUE TITLE
.NET Core - upgrade log4net, NLog, Serilog logging integration libraries

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#128]
These are still yet to be touched.

PR the `netcore` branch.

**Comment by jeremymeng** [comment]
log4net porting PR: https://github.com/apache/log4net/pull/16

**Comment by jonorossi** [comment]
Thanks for the links, I had been following those. As you probably saw Serilog 2.0.0 alphas have been out for a while now.

**Comment by jeremymeng** [comment]
I am working on Serilog integration.

**Comment by jonorossi** [comment]
FYI, NLog released alpha1 on the January 14: https://www.nuget.org/packages/NLog/4.4.0-alpha1.

**Comment by jeremymeng** [comment]
Thanks @jonorossi I didn't know about that.  I gave it a try but it looks like they don't support `dotnet5.4` yet.  I will see what I can do.

**Comment by jeremymeng** [comment]
I am on NLog integration.  There's a alpha-2 package that supports dotnet5.4 now.  However it failed the one and only NLog integration unit test. The same kind of failures are also seen in NLog unit tests (Dnx).

**Comment by hikalkan** [comment]
I created a nuget package to integrate Castle.LoggingFacility package with Microsoft.Extensions.Logging package. See: https://github.com/volosoft/castle-logging-ms-adapter

**Comment by jonorossi** [comment]
log4net, NLog and Serilog have been upgraded (#199) to the newest versions.

**Comment by hikalkan** [comment]
Thank you for that. When can this be released?

**Comment by jonorossi** [comment]
@hikalkan I'll have a beta release out in the next couple of days, just a few more things to sort out, RTM should hopefully follow fairly quicker afterwards.

**Comment by hikalkan** [comment]
Thank you very much for informing. This was one of the most asked questions to me since my framework (https://github.com/aspnetboilerplate/aspnetboilerplate) depends on castle logging facility.
