### ISSUE TITLE
.NET Core - migrate from csproj to project.json

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#134]
One of the things I was wondering late last year is if we should kill all of our csproj files and provide our support for .NET 3.5, 4.0 and 4.5, as well as Mono via project.json. The MSBuild hooks we've got in our csproj files are painful, and I'd love if we could push MSBuild out to just coordinating the MSBuild or out completely and just use a shell script.

1. Am I missing something where this is a bad idea?
1. It seems the MSBuild team want to support .NET Core, do MSFT employees know something I don't where it is acceptable to use MSBuild for .NET Core?
1. Can we re-implement the functionality we've currently got in our MSBuild hooks with project.json. e.g. remove AssemblyInfo generation (#133), dependency selection per platform.

**Comment by rjdevereux** [comment]
For point 2, I think they plan on supporting Core with xproj files which are the new csproj for VS.  There doesn't seem to be too much information about them yet.

**Comment by jonorossi** [comment]
@rjdevereux as far as I know xproj files are just there to give the Visual Studio project system a way of modelling these new project.json projects, they don't have any of the hooks we had to make to get conditional dependencies and the likes with csproj files, because they aren't based on the c# targets file but a DNX one.

The hooks we made aren't great, for example most don't work in Xamarin Studio, even though they are valid MSBuild the IDEs do struggle working with them a bit and it would be great if we didn't need all the magic to actually get things to work.

**Comment by jeremymeng** [comment]
@jonorossi 
It is possible to [use MSBuild to target .NET Core](http://aka.ms/porttocore).  However I am not sure we want that because we already got `project.json`-based projects running.  Also the project-to-project reference scenario from `project.json` project (the dnx test project) to the MSBuild project might not work.

For point 3. It might be hard or impossible to have variables in the assembly information when using `project.json`.  Dependencies shouldn't be a problem as we could move to reference NuGet packages

Third option is to have MSBuild projects and `project.json` projects together like current state.  We will need to update the nuspec file to include the output from .NET Core build.  It would make little sense to have two types of projects though, if one type works.

**Comment by jonorossi** [comment]
@jeremymeng ignoring assembly info files, do you see any blockers from us doing this? Do you know how we would migrate our Mono build and unit test runs?

@jamesathey will this cause problems supporting Xamarin.Android in this short term? @jeremymeng do you know where the DNX support for Xamarin.Android is at?

**Comment by jeremymeng** [comment]
> Do you know how we would migrate our Mono build and unit test runs?

I don't know much about the Mono builds.  Could you please provide more details?

> do you know where the DNX support for Xamarin.Android is at?

According to the [Net Platform Standard doc](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#observations), `netstandard1.3` (`dotnet5.4` which we target now) would support Xamarin platforms.

**Comment by jonorossi** [comment]
> Do you know how we would migrate our Mono build and unit test runs?

We basically run the builds like we do for MSBuild on Windows, except we run `xbuild` as an entrypoint and there are a couple of conditionals in the MSBuild based build scripts to handle platform differences like running nunit-console. 

You might have seen this note in the README:
> The `__MonoCS__` symbol is used only in unit tests when compiled on Mono to work around Mono defects and non-Windows differences, however we are trying to move away from platform specific symbols as much as possible.

I was slowly getting rid of the conditional compilation in the unit tests and replacing them with the `[Platform]` attribute from NUnit once I had confirmed we couldn't fix the problem, see #94 for more details on the test.

**Comment by jonorossi** [comment]
> According to the Net Platform Standard doc, netstandard1.3 (dotnet5.4 which we target now) would support Xamarin platforms.

@jeremymeng could you add your comment and how you determined dotnet5.4 and netstandard1.3 are equal (it isn't mentioned in that document) to #135, that is the task we are tracking adding support for Xamarin.Android, thanks.

**Comment by jeremymeng** [comment]
@jonorossi Do we absolutely need to build using Mono compiler, or would it work if the `project.json` project also targets a framework (`net451`?) that is compatible with Mono, then run the built tests using Mono?

**Comment by jonorossi** [comment]
@jeremymeng since the Mono guys are moving to Roslyn anyway I don't see any hard requirement to use their current compiler. The Castle Project has always had a pretty fluid concept of support for Mono over the years, things worked in the earlier MonoRail days however Mono hasn't been "officially" tested or supported until I got a Linux CI server set up last year and got things compiling again and the unit tests cleaned up because we were getting a few bugs reports for Mono.

As long as we transition the remaining `__MonoCS__` symbols into runtime conditionals/attributes as per https://github.com/castleproject/Core/issues/134#issuecomment-194183027, we should be fine to just run the tests on the Mono runtime but all compilation to occur on .NET Core.

**Comment by jeremymeng** [comment]
@jonorossi I will look into replacing `__MonoCS__` with runtime-check first.

**Comment by jeremymeng** [comment]
I've heard that NuGet v3 support is coming to Mono xbuild: https://github.com/mono/mono/pull/2776. With that `xbuild` will be able to build MSBuild-based .NET Core projects.  

Another alternative is to move the project.json project back to a csproj one.  It would supports both MSBuild and xbuild.  But I am not sure about the test project yet (I am trying to get more information on that.)

**Comment by rjdevereux** [comment]
Can this thread be closed?  Sounds like project.json is not surviving in RTM.

**Comment by jonorossi** [comment]
@rjdevereux yes, I think we should close this issue now that project.json will be killed. We'll have to see how the multi-targeting support is handled to allow us to migrate from our customised MSBuild csprojs to the new csprojs so we can remove our project.json files post-RTM when the tooling arrives.
