### ISSUE TITLE
Update Serilog library version to 2.0 and fix failing test

### ISSUE THREAD

**Issue by jeremymeng** [castleproject/Core#137]
As the .NET Core port requires v2.0, it make sense to have the same version for Desktop. 

(I wonder why the dependencies are not managed by NuGet.)

There's [a breaking change](https://github.com/serilog/serilog/pull/571) in v2.0 

which would break one Serilog integration test: https://github.com/castleproject/Core/blob/v3.3.3/src/Castle.Core.Tests/SerilogIntegration/SerilogTests.cs#L163-L183

**Comment by jonorossi** [comment]
@jeremymeng our vendored dependencies pre-date NuGet, and the early versions of NuGet sucked real bad so we didn't want to add that pain. I'd like to start the discussion on #134 which would turn that around and make everything more consistent to how the .NET Core stuff works.

**Comment by jonorossi** [comment]
#134 has been closed because project.json won't survive, however we need to still look at upgrading the dependencies used by the .NET Framework builds.

**Comment by jeremymeng** [comment]
The current build/project setup makes updating dependencies harder.  How about switching to NuGet dependencies?  Will probably need to split Castle.Core project into three projects: net35, net40, and net45.

**Comment by jonorossi** [comment]
@jeremymeng yep I agree the current extended MSBuild set up makes it hard to integrate NuGet. We used to have `-vs2005`, `-vs2008` and `-vs2010` project files to account for the incompatible Visual Studio file formats, I don't think we want to go back there, it was very painful when you add just a single new file.

I think we should just wait until the new Visual Studio tooling comes which integrates .NET Core and retargeting support, then we'll only need a single place for dependencies to be defined. With that in mind let's continue with #188.

**Comment by jonorossi** [comment]
Serilog has been upgraded, closing.
