### ISSUE TITLE
.NET Core - consolidate version numbers

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#152]
Now that we've got hardcoded version numbers in 5 new `project.json` files, and now also in `CommonAssemblyInfo.cs` in addition to Settings.proj let sort something out.

Can we just have all version numbers stored in Git as `0.0.0` and have the CI build replace the version number in the files like it currently does for our current nuspecs. If so we could get the build number into the `AssemblyInformationalVersion` again.

**Comment by blairconrad** [comment]
Do the netcore projects require the version in `project.json`, or could they read the versions from a `CommonAssemblyInfo.cs` file like I'm used to in old-style .NET?

If the latter, I've an idea in mind that I'd flesh out and present when not at work…

**Comment by jonorossi** [comment]
I suspect the DNX tools require it in there to build the NuGet package.

/cc @jeremymeng

**Comment by jonorossi** [comment]
If we get rid of the csproj files in #134, then I'm pretty sure we don't need the version attributes in `CommonAssemblyInfo.cs`.

**Comment by blairconrad** [comment]
Re the dnx NuGet building, "darn".
Yes, if the versions are required in the `project.json` files, then getting out of `CommonAssemblyInfo.cs` makes sense. I'd just thought we could have a cleaner solution with them _in_ `CommonAssemblyInfo.cs` if we didn't need in `project.json` **and** if you wanted to continue synchronizing versions across the projects.

**Comment by jonorossi** [comment]
Yes, we'll keep all the packages versioned in lock-step otherwise it will be a nightmare and achieve nothing, they are only separate packages to separate out the dependencies because each assembly is tiny. If we do get rid of csproj it would leave us with versions only in project.json files because Settings.proj would go, then maybe a little script could update them all at once.

**Comment by blairconrad** [comment]
@jonorossi, we currently build the nupkg by supplying an explicit version number, as you noted above. So mightn't we be able set the `project.json` versions all to 0.0.0 (for now? for a while)? The attributes in `CommonAssemblyInfo.cs` are respected. I'm working on something, if you're open to this.

**Comment by jonorossi** [comment]
If we went with something like #153 I've got a bunch of comments on implementation, however it feels like we are pushing against the tooling pretty hard to do something like that.

Couldn't we just [set `DNX_BUILD_VERSION` instead to get the build number](https://github.com/aspnet/dnx/blob/124f1ffb610e5bd1838768c7bc2da723d522b45c/src/Microsoft.Dnx.Runtime/ProjectReader.cs#L44) into at least the package version and leave the `M.m.p` version in each project.json. This would mean we wouldn't be working against the new tools (which are still evolving and `global.json` might get a version field or we get another environment variable in https://github.com/dotnet/cli/issues/571) and would mean we'd get rid of the version from `CommonAssemblyInfo.cs` and `Settings.proj`.

**Comment by jonorossi** [comment]
We might consider leaving `AssemblyVersion` in `CommonAssemblyInfo.cs` hardcoded to prevent binding redirect problems on .NET Framework.

This is what Serilog has done: https://github.com/serilog/serilog/blob/dev/src/Serilog/Properties/AssemblyInfo.cs#L4

**Comment by blairconrad** [comment]
@jonorossi, `DNX_BUILD_VERSION` seems cool for setting the project version, and if/when the project.json builds all the framework versions and packs them into a multi-targeting package, it'll be quite handy. I'm happy to make that change. It does not help get the build number in `AssemblyInformationalVersion`, though.

Ah. Interesting trick for the `AssemblyVersion`. What do you like for a value?

**Comment by jonorossi** [comment]
I think we need to sort out #134 first otherwise we'll be trying to implement this while keeping the MSBuild based projects working. We should decide what we are doing here knowing full well if we have to continue supporting MSBuild and project.json based project formats.

**Comment by jonorossi** [comment]
@blairconrad maybe we can do something like this in our CI builds, with 0.0.0 being set in those files committed to Git?
https://github.com/c3-ls/CastleWindsor-MsExtensionsIntegration/blob/master/build-set-version.ps1

**Comment by blairconrad** [comment]
which would then leave the committed files in a modified state on the disk?

**Comment by jonorossi** [comment]
@blairconrad yes, but only on the build server which gets cleaned off after the build finishes. On a developer's machine when they build, the output always gets 0.0.0 as the version (indicating an unofficial build), a developer shouldn't run the extra version replacing script. Makes sense?

**Comment by blairconrad** [comment]
It does. In my experience it's an atypical workflow, but I'm more accustomed to working with projects whose build server _don't_ start with a fresh workspace for each build. (Something I've argued against unsuccessfully, but at the Day Job we have big projects, and there is a time savings… anyhow.)

I'm happy to pursue this approach, if you'd like me to work on it before #134 is complete. (I took a look at that issue with the idea of helping out, but wasn't sure where to jump in between you and @jeremymeng.)
If we finish this first, it may mean a small amount of rework when #134 comes in, but probably not much.

**Comment by jonorossi** [comment]
Oh, incremental builds, those are obviously unneeded for Castle Core since our project builds in something like 3 seconds, and the rest is unit test time. I've worked with incremental builds with massive products before and it definitely saves time but without the source code being marked readonly on disk the pain is too great when things don't work exactly right.

Happy for you to work on this now, I've got no idea if DNX will even allow a 0.0.0 package version but worth giving a shot. The [Serilog build script](https://github.com/serilog/serilog/blob/dev/Build.ps1) might help since theirs seems to work well, but they don't replace the version in project.json. I agree that the rework should be minimal but worthwhile prototyping this to see what is possible.

#134 really is just a discussion so far.

**Comment by blairconrad** [comment]
Cool. I'll see about rewriting `project.json`s (and a simpler version of the `CommonAssemblyInfo.cs`).

**Comment by blairconrad** [comment]
@jonorossi, since my last comment, #153 was merged, so I think this is closed? I hadn't put a "fixes #152" in the PR, so this is probably my fault.
