### ISSUE TITLE
Package on NuGet.org broken

### ISSUE THREAD

**Issue by davidfowl** [castleproject/Core#175]
https://www.nuget.org/packages/Castle.Core/4.0.0-alpha001

![image](https://cloud.githubusercontent.com/assets/95136/14579090/d09d1cde-0351-11e6-9194-8f6f2add5760.png)

Notice the Unsupported0.0. This happens when you use an old version of NuGet.exe that doesn't recognize the framework being packed. It's an awful bug but this package is broken.

**Comment by jonorossi** [comment]
Fixed the other day in #174.
