### ISSUE TITLE
Performance issues with mixin

### ISSUE THREAD

**Issue by sebastienros** [castleproject/Core#178]
I am using this code to generate a dynamic proxy with a mixin, and no interceptors, on .NET Core.

```
    var generator = new ProxyGenerator();
    var options = new ProxyGenerationOptions();
    options.AddMixinInstance(new ShapeImplementation(shapeType));
    shape = generator.CreateClassProxy(type, options) as IShape;
```

I can only run about 20 requests per seconds with this code, and 30 times more without. Is there any best practice I am missing? I have a mixin implementation that I want to inject in a DP in order to get a sub-class of `type`. `ShapeImplementation` has some interfaces that I want to keep on the final object. 

It works as expected but it's really slow.

**Comment by kenegozi** [comment]
Cache the proxy generator

Ken Egozi.
http://kenegozi.com/ <http://kenegozi.com/blog>

**Comment by sebastienros** [comment]
Thanks, that fixed it, and also found it in the documentation.
