### ISSUE TITLE
Proxies of objects with get/set properties that implement interface with get properties results in two properties

### ISSUE THREAD

**Issue by heaths** [castleproject/Core#179]
For mockability we have a number of "read-only" interfaces like so:

``` csharp
interface IFoo
{
  string Bar {get;}
}
```

But the objects that implement them may be "read/write" like so:

``` csharp
class Foo : IFoo
{
  public string Bar {get; set;}
}
```

When deserializing mock objects of these types (using Moq), Json.NET was failing and after debugging I see that the generated proxy has two properties with the same name (didn't even realize that was possible with the CTS!).

No amount of setups using Moq seemed to work around getting or setting values. But since the C# compiler knows how to collapse the properties, it seems proxy generation should as well; i.e., only a single property is generated with whatever the implementing class defines.

**Comment by jonorossi** [comment]
@heaths any chance you could provide a unit test using only DynamicProxy (without Moq or JSON.NET)?

**Comment by stakx** [comment]
@heaths: Hailing from Moq here. We've just recently fixed a long-standing regression in Moq that caused lots of problems with interfaces and member redeclarations in derived types. That bug might have caused the issue you're describing, too; see https://github.com/moq/moq4/pull/381.

If you'd like to rule out this (now fixed) bug as a possible error source, update to Moq version 4.7.63 or later and see if the problem goes away.

I'd also be interested in seeing repro code. Feel free to open an issue over at https://github.com/moq/moq4/issues (unless you've already ruled out Moq as a possible error source, of course).

**Comment by heaths** [comment]
Sorry @jonorossi, this had slipped under my radar but @stakx made a blip. I'll try to repro the problem with the latest Moq4 as suggested, but doing so without Moq would take quite a bit more. I'm not sure what all moq does (without further reviewing their code) but it was clear the proxy itself appeared to have multiple implementations of such a property. Let me start with @stakx's suggestion and I'll go from there.

**Comment by heaths** [comment]
Unfortunately, I can't seem to repro this using all the same versions of packages we had back then. If only I hadn't failed to notice your request: I'd probably have remembered exactly how to repro this. I've tried several ways based on our current code structure but it's not working, so feel free to resolve. If I think of how I did this before, I'll reopen with an example.

**Comment by jonorossi** [comment]
@heaths great to hear, hopefully there is no bug 😉 . Let us or the Moq guys know if you run into it again in the future.
