### ISSUE TITLE
Test XmlAdapterAcceptanceTestCase.Can_Write_Nillables_To_Standard_Xml_Serialization should verify the deserialized object

### ISSUE THREAD

**Issue by jeremymeng** [castleproject/Core#189]
But it is verifying on the original object instead.

https://github.com/castleproject/Core/blob/master/src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlAdapterAcceptanceTestCase.cs#L1191

**Comment by jonorossi** [comment]
@jeremymeng no need to create an issue **and** a PR. Thanks.
