### ISSUE TITLE
Upgrade NLog to 4.5 RTM for .NET Core support

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#200]
We are currently using NLog 4.4.0-beta13 to get .NET Core support, we need to upgrade to an RTM version once it is released.

**Comment by jonorossi** [comment]
The main NLog .NET Core issue for 4.4 that hasn't been closed is https://github.com/NLog/NLog/issues/641.

**Comment by jonorossi** [comment]
New main issue for .NET Core support in NLog: https://github.com/NLog/NLog/issues/1559

**Comment by jonorossi** [comment]
The NLog guys have gone quiet since July so it might be time to drop NLog 4.4 beta support with .NET Core support from Castle Core 4.0 and revert back to NLog 4.3.x. It'll unblock us from not being able to release a 4.0 final.

Thoughts?

**Comment by jonorossi** [comment]
Looks like NLog guys have bumped their betas support .NET Standard from 4.4.x to 5.0.x.

**Comment by DixonDs** [comment]
Are there any estimates when Castle.Core 4.0 RTM will be released? We have a couple of libraries depended on it, which we keep as prerelease mainly because they have prerelease dependency Castle.Core

**Comment by jonorossi** [comment]
@DixonDs are you using NLog? This issue is about supporting NLog on .NET Core.

**Comment by DixonDs** [comment]
@jonorossi Sorry, that was probably a wrong issue to ask that question. I've just got an impression that it is the only outstanding issue that holding Castle.Core 4.0 release. Do you happen to have gitter.im channel?

**Comment by jonorossi** [comment]
@DixonDs no problem, nope no active chat room. I just added a log4net issue into the milestone too. I've just been swamped for the last few weeks so pull requests on these last two remaining issues would allow me to cut the release.

**Comment by thomaslevesque** [comment]
Hi @jonorossi, do you plan to release the logging integration packages along with the main library for 4.0? From what I understand, it might be a while before NLog is ready for .NET Core, and none of the integration projects have been migrated to .NET Core yet. It might be a good idea to release Castle.Core 4.0 alone for now, and release the integration packages later. What do you think?

(If I seem eager to see Castle.Core 4.0 released, it's because I am :wink:... it's about the only thing keeping us from releasing FakeItEasy 3.0)

**Comment by jonorossi** [comment]
@thomaslevesque yes, logging integration packages will be released as they have been in the betas. As per my comment on Nov 15th, this issue is only still in the milestone until we revert to a stable NLog for .NET 4.x.

Sorry about not getting the final release out, I kept snoozing Blair's GitHub comment notification email from last month where he said you guys weren't in a rush for it, didn't know you were ready to release. I'll try to get it sorted tomorrow.

**Comment by thomaslevesque** [comment]
@jonorossi thanks! I don't want to rush you, I was just wondering if something was keeping you from releasing.

**Comment by jonorossi** [comment]
@thomaslevesque no problem, I was hoping to get it done around Christmas. Just have to make the time to sort out the 3 remaining issues and cut the release.

**Comment by blairconrad** [comment]
You're good folk, @jonorossi.

**Comment by jonorossi** [comment]
NLog 4.4.0-beta13 is now unlisted and the 4.4.x line no longer supports .NET Core. I've upgraded to NLog 4.4.1 for the .NET Framework targets.

Removing this issue from our v4.0 milestone.

**Comment by fir3pho3nixx** [comment]
Looks like this one is back in play: https://www.nuget.org/packages/NLog/5.0.0-beta07

Should we jump after: https://github.com/castleproject/Core/issues/241

**Comment by jonorossi** [comment]
> Looks like this one is back in play: https://www.nuget.org/packages/NLog/5.0.0-beta07
> 
> Should we jump after: #241

I think we should wait until the final version so we don't get blocked releasing the next version with a beta version for .NET Framework.

**Comment by jonorossi** [comment]
> NLog 4.5 is RTM! NLog 4.5 adds structured logging and .NET Standard support/UPW without breaking changes!
> (https://twitter.com/NLogOfficial/status/978038367903539200)

**Comment by snakefoot** [comment]
Created PR #340
