### ISSUE TITLE
Support log4net integration on .NET Core

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#201]
This will miss the cut for v4.0 because log4net still doesn't support .NET Core: https://github.com/apache/log4net/pull/16

**Comment by mtraudt** [comment]
There is now a version of log4net (2.0.6) that targets netstandard1.3: https://www.nuget.org/packages/log4net-core-preview/

**Comment by jonorossi** [comment]
@mtraudt that package looks to be published by a third party and is not supported by the upstream project.

**Comment by iluzyanin** [comment]
The official package with .Net core support is there now: https://www.nuget.org/packages/log4net/2.0.6

**Comment by jonorossi** [comment]
log4net 2.0.7 was released on January 5th to fix the NuGet package dependencies being wrong.

I've attempted to add support for .NET Core with our log4net integration, however I ran into the following problems with the .NET Core build:
- `XmlConfigurator.Configure` and `XmlConfigurator.ConfigureAndWatch` now require a `log4net.Repository.ILoggerRepository`
- `LogManager.GetLogger` needs a repository name or repository assembly
- `LogManager.GetRepository` needs a repository name or repository assembly

I ran out of time to implement this myself and I don't use it myself. This issue is already tagged `up-for-grabs`, so a pull request is welcomed and we can make another release.

If someone wants to pick this up you'll need to add the xproj back to the NetCore solution and edit the project.json for the unit test project to reference the log4net project and remove the file exclusion.

**Comment by fir3pho3nixx** [comment]
@jonorossi - I can verify this, I ran into the same issues. What are your thoughts on how you want to inject the repository? I cheated with some default repository hack. Would be happy to fish it out and submit a PR for this.

**Comment by jonorossi** [comment]
> What are your thoughts on how you want to inject the repository? I cheated with some default repository hack. Would be happy to fish it out and submit a PR for this.

I really can't remember any of it, happy to review a pull request.

**Comment by snakefoot** [comment]
Created PR #340
