### ISSUE TITLE
Use IProxyGenerator interface for Dependency Injection

### ISSUE THREAD

**Issue by tmm360** [castleproject/Core#215]
Can you add an interface IProxyGenerator to the ProxyGenerator class?

I'm building a DI compliant service, and this should help me, instead of statically link the class with `new ProxyGenerator()`, or create a wrapper to inject that does the same. Thank you.

**Comment by jonorossi** [comment]
@tmm360 most people are likely to wrap the `ProxyGenerator` in their own class that does a bunch of other stuff, however I can't think of a reason we shouldn't have an interface so you can do this. Just make sure you make it an application-wide singleton so you only get a single `ModuleScope`.

I've added the interface in #217, it'll be released in 4.0.0.
