### ISSUE TITLE
Null is not a valid constant value for this type in method with nullable optional parameters

### ISSUE THREAD

**Issue by saitonakamura** [castleproject/Core#216]
When trying to intercept a call to method that has optional parameter with `Nullable<T>` and `null` default value, it throws Exception `Null is not a valid constant value for this type`
Found a gist that illustrates the issue [https://gist.github.com/pawelpabich/7371055](https://gist.github.com/pawelpabich/7371055)

I'm using `Castle.Core` package version `3.2.1`

**Comment by jonorossi** [comment]
@saitonakamura I'm pretty sure this is fixed in 4.0.0, we've had other bug reports with optional parameters which we've fixed. Could you give your example code a try with it.

**Comment by jonorossi** [comment]
@saitonakamura this specific issue was fixed (17c1596b1e7f547eaa15479ada0b793a306ab991) in 3.2.2 (the only change in that release and released late 2013), however we've changed the handling of optional parameters completely in 4.0.0. You should be fine to just update to a newer 3.x release.
