### ISSUE TITLE
DynamicProxyGenAssembly2 hardcoded name

### ISSUE THREAD

**Issue by maxim-boligatov** [castleproject/Core#218]
Is it possible to make the name "DynamicProxyGenAssembly2" configurable in some way?
As I can see for now it is hardcoded in source code...
But I have to specify this attribute in assemblies containing business logic.
So it will be good option to control the name (be able to change it).

P.S. I am using mocking frameworks based on Castle (for example NSubstitute).

**Comment by jonorossi** [comment]
@maxim-boligatov the default is hardcoded, if you create your own `ModuleScope` you should be able to specified it as [we do in our unit tests](https://github.com/castleproject/Core/blob/2acd42b27e3fae643f203d9a3ee1cfdb3a7e7bfd/src/Castle.Core.Tests/ModuleScopeTestCase.cs#L336-L345), however it isn't something I've seen any consumers actually do. This obviously would mean you'd have to maintain your own fork of NSubstitute.
