### ISSUE TITLE
DynamicProxy: ParameterBuilder.SetConstant doesn't completely support C#, leading to exceptions

### ISSUE THREAD

**Issue by cyanite** [castleproject/Core#220]
Microsoft's `System.Reflection.Emit.ParameterBuilder.SetConstant` method, used when defining methods with parameters with default values in `Castle.DynamicProxy.Generators.Emitters.MethodEmitter.DefineParameters` unfortunately (and inexplicably) doesn't support the full C#-standard with respect to what kinds of default parameters and expressions are allowed. This results in an exception from the framework when trying to create a proxy for a type with a method with certain default parameters.

The `System.Reflection.Emit.ParameterBuilder.SetConstant` method supports:
> defaultValue is restricted to the following types: Boolean, SByte, Int16, Int32, Int64, Byte, UInt16, UInt32, UInt64, Single, Double, DateTime, Char, String, and Enum.

The C#-standard (here 5.0) has no direct restriction on the *type*, but for the expression supports:

> The expression in a default-argument must be one of the following:
> * a constant-expression 
>* an expression of the form new S() where S is a value type
>* an expression of the form default(S) where S is a value type
>
> The expression must be implicitly convertible by an identity or nullable conversion to the type of the parameter.

This means that the following is valid C# code but can't be emitted using `ParameterBuilder`:
`void Test(decimal x = 42M) { }`

Since this is, in my view, a bug in the framework, I don't know what the solution should be. Perhaps check for the list of allowed types and simply skip the code to add default values if it doesn't match.

**Comment by jonorossi** [comment]
@cyanite yep, we've run into various problems with SetConstant in the 2 years. We worked around the problems with decimal in #87, then decided to completely remove optional parameters in #141. These changes are in v4.0.
