### ISSUE TITLE
v4 Beta 2 issue creating a container

### ISSUE THREAD

**Issue by atodd-geoplan** [castleproject/Core#224]
I have been forced down the path of updating to the beta 2 of Castle.Core 4 in order to keep using the latest version of Serilog in an asp net core project.

Seems to be a big problem simply creating a new container. Any ideas?

`var container = new WindsorContainer();`

> An exception of type 'System.MethodAccessException' occurred in Castle.Windsor.dll but was not handled in user code: Additional information: Attempt by method 'Castle.MicroKernel.SubSystems.Configuration.DefaultConfigurationStore..ctor()' to access method 'System.Collections.Generic.Dictionary`2<System.__Canon,System.__Canon>..ctor()' failed.

**Comment by jonorossi** [comment]
@atodd-geoplan no testing has been done to determine if Windsor 3.x is compatible with Castle Core 4.x, so it very likely doesn't work. Could you provide the full exception details as I don't see any mention of Castle Core in that stack trace.

**Comment by jonorossi** [comment]
We need to check Windsor before cutting 4.0, and maybe release a new Windsor NuGet package that states it isn't compatible with Castle Core 4.0.

**Comment by jonorossi** [comment]
Closing in favour of https://github.com/castleproject/Windsor/issues/161 as this will be resolved by Windsor.
