### ISSUE TITLE
Redirecting the log to Nlog

### ISSUE THREAD

**Issue by fasterfish** [castleproject/Core#226]
My testing project uses Nlog as a logger.

How can I redirect TestStack.White messages from Castle.Core to Nlog?

An example of a base class that I use:

```csharp
using Castle.Core.Logging;
using NLog;
using TestStack.White.Configuration;

public class BaseTest
{
    public BaseTest()
    {
        CoreAppXmlConfiguration.Instance.LoggerFactory = new ConsoleFactory(LoggerLevel.Error);
    }

    protected Logger logger
    {
        get
        {
            return LogManager.GetCurrentClassLogger();
        }
    }
}
```

**Comment by jonorossi** [comment]
This sounds like a question for the White project, however it looks like you tried that without a response (https://github.com/TestStack/White/issues/517). It is best to ask questions like this on StackOverflow.

Guessing from your code snippet, you need to reference `Castle.Services.Logging.NLogIntegration.dll` and set White's `LoggerFactory` property to a new instance of `NLogFactory`.

Here is a question on StackOverflow from last month asking the same thing: http://stackoverflow.com/questions/41103932/capturing-log-output-from-library-using-castle-core-logging

**Comment by jonorossi** [comment]
With that StackOverflow link, ignore the Windsor logging facility info you don't need Windsor for the logging integration.

**Comment by fasterfish** [comment]
Thank you. It's help me:
```
using Castle.Services.Logging.NLogIntegration;
using NLog;
using TestStack.White.Configuration;

public class BaseTest
{
	public BaseTest()
	{
		CoreAppXmlConfiguration.Instance.LoggerFactory = new NLogFactory();
	}

	protected static ILogger logger
	{
		get
		{
			return LogManager.GetCurrentClassLogger();
		}
	}
}
```
