### ISSUE TITLE
Castle.Core DefaultTypedFactoryComponentSelector Equivalent

### ISSUE THREAD

**Issue by EdsonF** [castleproject/Core#233]
I'm porting a .net 4.5 project over to .net core and I can't find an equivalent in Castle Windsor to DefaultTypedFactoryComponentSelector.

Has a Castle.Core DefaultTypedFactoryComponentSelector Equivalent been added to the framework yet?

**Comment by jonorossi** [comment]
@EdsonF this is the Castle Core project, not Castle Windsor. Castle Core has never had that class, Windsor's typed factory facility is still part of Windsor. Note though that Windsor doesn't support .NET Core yet, see https://github.com/castleproject/Windsor/issues/145.
