### ISSUE TITLE
dynamic proxy performance,it is too slow?

### ISSUE THREAD

**Issue by fatli** [castleproject/Core#234]
use RealProxy,Castle DynamicProxy and a another DynamicProxy(i don't know it's name.like amost use Emit implement dynamic proxy),I compare the use time.castle dynamic proxy ,it's sloweast.
the console output:
this ,Castle DynamicProxy version is lasteast.install from nuget.and i only  Initialize once.

Please enter the loop invoke method count:
100
Not Use Proxy:0
Use Castle.DynamicProxy:128
RealProxy:2
TestDymaticProxy:21
Please enter the loop invoke method count:
900
Not Use Proxy:0
Use Castle.DynamicProxy:20
RealProxy:5
TestDymaticProxy:2
Please enter the loop invoke method count:
10000
Not Use Proxy:0
Use Castle.DynamicProxy:114
RealProxy:51
TestDymaticProxy:20
Please enter the loop invoke method count:
100000
Not Use Proxy:3
Use Castle.DynamicProxy:1151
RealProxy:423
TestDymaticProxy:197
Please enter the loop invoke method count:

**Comment by jonorossi** [comment]
@fatli you will need to provide more information for any investigation. Please include the actual code for each library you are testing.

**Comment by fatli** [comment]
@jonorossi 

 `     class Program
    {
        #region Init Castle Dynamic Proxy
        static ProxyGenerator proxy = new ProxyGenerator();
        static CDP_Interceptor PInterceptor = new CDP_Interceptor();
        #endregion

        static void Main(string[] args)
        {
            while (true)
            {
                Console.WriteLine("Please enter the loop invoke method count:");
                UInt32 number = 0;
                if (UInt32.TryParse(Console.ReadLine(), out number))
                {
                }
                else
                {
                    continue;
                }
                System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();

                #region Not use Proxy
                sw.Start();
                for (int i = 0; i < number; i++)
                {

                    Test test1 = new Test();
                    test1.Show();

                }
                Console.WriteLine("Not Use Proxy:" + sw.ElapsedMilliseconds.ToString());
                #endregion

                #region Use Castle Dynamic Proxy
                sw.Restart();

                for (int i = 0; i < number; i++)
                {
                    PInterceptorProxy();
                }
                Console.WriteLine("Use Castle.DynamicProxy:" + sw.ElapsedMilliseconds.ToString());
                #endregion

                #region RealProxy
                sw.Restart();

                for (int i = 0; i < number; i++)
                {

                    RealProxy();
                }
                Console.WriteLine("RealProxy:" + sw.ElapsedMilliseconds.ToString());
                sw.Restart();

                #endregion

                #region UnknowDynamic Proxy
                for (int i = 0; i < number; i++)
                {
                    new UnknowDynamicProxy().TestDymaticProxy();
                }
               

                Console.WriteLine("TestDymaticProxy:" + sw.ElapsedMilliseconds.ToString());
                #endregion
            }
        }

        private static void RealProxy()
        {
            var instance = new RealProxyInstance<Test>(new Test());
            Test test = instance.GetTransparentProxy() as Test;
            test.Show();


        }

        private static void PInterceptorProxy()
        {
            Test test = proxy.CreateClassProxy<Test>(PInterceptor);
            test.Show();

        }
    }
    #region Castle Dynamic Proxy
    public class CDP_Interceptor : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.Proceed();
        }
    }

    #endregion

    #region RealProxy
    public class Test : MarshalByRefObject
    {
        public virtual void Show()
        {
        }
    }

   
    public class RealProxyInstance<T> : RealProxy
    {
        private readonly T _decorated;
        public RealProxyInstance(T decorated)
    : base(typeof(T))
        {
            _decorated = decorated;
        }
        public override IMessage Invoke(IMessage msg)
        {
            var methodCall = msg as IMethodCallMessage;
            var methodInfo = methodCall.MethodBase as MethodInfo;
            var result = methodInfo.Invoke(_decorated, methodCall.InArgs);
            return new ReturnMessage(result, null, 0,
              methodCall.LogicalCallContext, methodCall);

        }
    }
    #endregion

    #region UnknowDynamicProxy
    public class UnknowDynamicProxy
    {
        public void TestDymaticProxy()
        {
            var computer = (UnknowDynamicProxy)DynamicProxy.SecurityProxy.NewInstance(new UnknowDynamicProxy());
            computer.GetPrice2();
        }

        public void GetPrice2()
        {
        }
    }
    #endregion`

**Comment by fatli** [comment]
I found  the   "CreateClassProxy " method used a lot of time.

**Comment by jonorossi** [comment]
In your benchmark your test class (`Test`) inherits `MarshalByRefObject`, this hurts Castle DynamicProxy performance considerably, without that you can see that Castle DynamicProxy compares well with the CLR's built-in limited remoting-based proxying.

I couldn't test your 3rd library as I don't know what it is. I ran 1000 iterations twice to ensure that Castle DynamicProxy had generated its proxy type on first call which is cached.

| # | Iterations | No Proxy | RealProxy | C.DP  | C.DP w/ MBRO | UnknownLib |
| - |       ---: |     ---: |      ---: |  ---: |         ---: |       ---: |
| 1 |      1,000 |        0 |         2 |    13 |          140 |          ? |
| 2 |      1,000 |        0 |         2 |     3 |            7 |          ? |
| 3 |     10,000 |        0 |        22 |    31 |           68 |          ? |
| 4 |    100,000 |        2 |       239 |   323 |          594 |          ? |
| 5 |  1,000,000 |       23 |     2,475 | 3,280 |        6,805 |          ? |

This benchmark aside, I'm sure there are more micro-optimisations we could make to Castle DynamicProxy, however those really should come from real world scenarios rather than this type of brute force benchmark.

**Comment by fatli** [comment]
@jonorossi  Thanks.
