### ISSUE TITLE
Add method to describe actions needed to intercept inaccessible members

### ISSUE THREAD

**Issue by blairconrad** [castleproject/Core#235]
From https://github.com/FakeItEasy/FakeItEasy/issues/341#issuecomment-283933437, whose text I paraphrase here.

----

In #30, I beefed up the messages generated when we try to proxy a type that's not accessible to DynamicProxyGenAssembly2. I realize that Castle.Core doesn't have a need to generate an exception when a _member_ is inaccessible, but it would be very handy for FakeItEasy (and possibly other clients) to have access to Castle.Core methods in order to improve the messages seen by their clients when they try to configure an `internal` method.

----

@jonorossi has suggested that `ExceptionMessageBuilder` probably should have gone under the DynamicProxy namespace, since it's similar to `Castle.DynamicProxy.ProxyUtil`.

Team CastleProject, I'd be happy to work on this (although not for a few days or so), if it suits you. While I'm at it, would you like  me to add an alternative for `ExceptionMessageBuilder` in `DynamicProxy`?

I'm not sure what the Castle project's policy is on obsoleting members, but if it's liberal, we could start obsoleting `Castle.Core.Internal.ExceptionMessageBuilder`.

**Comment by jonorossi** [comment]
> has suggested that ExceptionMessageBuilder probably should have gone under the DynamicProxy namespace, since it's similar to Castle.DynamicProxy.ProxyUtil

Not quite, you merged two comments 😄 . Yes it should have gone under the DP namespace because it is a DP thing; when I was talking about `ProxyUtil` I was referring to the idea that we might want a utility function like those public ones for consumer use (maybe something like IsAccessible) that could return a message if it isn't accessible explaining why (i.e. calling the ExceptionMessageBuilder).

> I'm not sure what the Castle project's policy is on obsoleting members

`ExceptionMessageBuilder` is actually marked internal, just change it as needed.

**Comment by blairconrad** [comment]
> `ExceptionMessageBuilder` is actually marked internal, just change it as needed.

Bother. As I was heading to bed, I had a nagging feeling that I'd made that mistake. Thanks.

**Comment by blairconrad** [comment]
Sorry, @jonorossi. I may have confused things in a way even more different than I thought. 
`Castle.DynamicProxy.Internal.InternalsUtil.IsAccessible` exists, and is public (in fact, FakeItEasy uses it). If anything's a candidate for deprecation, it's this.
If you like, and it fits the project rules, I can start work on it.

Either way, if it doesn't offend, I'll take your idea of adding an `IsAccessible` to `ProxyUtil`. I'm thinking
`bool IsAccessible(MethodBase method, out string reasonMethodIsNotAccessible)`, but welcome alternatives, either before or after I send a PR.

**Comment by jonorossi** [comment]
@blairconrad apologies for not getting back to you last week on your proposal, I'll look at your pull request today.

**Comment by blairconrad** [comment]
No rush or need for apologies, @jonorossi. I appreciate your efforts. In the meantime, I'll rebase, because 
![image](https://cloud.githubusercontent.com/assets/3275797/23838853/20665000-0770-11e7-9672-75afa761c1c8.png)
