### ISSUE TITLE
NuGet package has wrong dependency from the "System.ComponentModel.TypeConverter" package

### ISSUE THREAD

**Issue by San4es** [castleproject/Core#239]
See [the Castle.Core.nuspec file](https://github.com/castleproject/Core/blob/49cf7e2e937d653824f2b3ff8f7c197ed4fbecff/buildscripts/Castle.Core.nuspec#L23):

    <dependency id="System.ComponentModel.TypeConverter" version="4.0.1" />

The "System.ComponentModel.TypeConverter" package with the 4.0.1 version [does not exist](https://www.nuget.org/stats/packages/System.ComponentModel.TypeConverter?groupby=Version).

It seems that the "4.1.0" version should be used (like in [project.json](https://github.com/castleproject/Core/blob/49cf7e2e937d653824f2b3ff8f7c197ed4fbecff/src/Castle.Core/project.json#L17))

**Comment by emgarten** [comment]
The dependency on the non-existent 4.0.1 package causes NuGet restore to float downwards. Each restore will try again to check if 4.0.1 exists on a source since it is the best match.

Restore caches the list of versions from http feeds for 30 minutes, but after that it will again make http requests to each feed looking for the package again.

I'm currently hitting this due to Moq 4.7.1's dependency on Castle.Core.

**Comment by jeremymeng** [comment]
Sorry [my fault](https://github.com/castleproject/Core/commit/799a24e36c23fd8ad3432e7ab23ac61032e53893#diff-b0c4b291114ac2c05230ced36ddaf78c).

@jonorossi I will submit a PR.  Do you have plan to new version on NuGet?

**Comment by fir3pho3nixx** [comment]
I have upgraded this package in the work I am doing to move all the build infrastructure over the new VS2017 tooling in #241.

Please see: https://github.com/fir3pho3nixx/Core/blob/master/src/Castle.Core/Castle.Core-VS2017.csproj#L26

If we go up to 4.3.0, do you think it will still be a problem?

**Comment by jeremymeng** [comment]
> If we go up to 4.3.0, do you think it will still be a problem?

No, if there's no plan to release a minor update then this fix is not necessary.

**Comment by jonorossi** [comment]
> Sorry my fault.

No problem, I'm surprised nuget.org doesn't verify that dependencies actually exist.

> I will submit a PR. Do you have plan to release a new version with this fix on NuGet?

My plan was to release a minor release with this fix after we've moved over the build process.

**Comment by jonorossi** [comment]
Fix is in v4.1.
