### ISSUE TITLE
GetUnproxiedInstance unexpected return when unproxy a modified instance

### ISSUE THREAD

**Issue by dgandini** [castleproject/Core#240]
`ProxyUtil.GetUnproxiedInstance` returns original instance of a changed object. Is it a bug? Is there any way to unproxy the modified instance?

I create an object instance, "wrap" it in a DynamicProxy and make some changes but I lost them when I call `ProxyUtil.GetUnproxiedInstance`.

Example: 
```
        static void Main(string[] args)
        {
            ProxyGenerator generator = new ProxyGenerator();
            TestClass entity = new TestClass(7);
            TestClass proxiedEntity = (TestClass)generator.CreateClassProxyWithTarget(typeof(TestClass), entity, new object[] { entity.Id }, new MyInterceptor());
            proxiedEntity.Id = 1; // change something

            var unproxiedEntity = (TestClass)ProxyUtil.GetUnproxiedInstance(proxiedEntity); // get Unproxied

            Console.WriteLine(entity.Id.Equals(7)); // OK (true) - original value without changes should be 7
            Console.WriteLine(proxiedEntity.Id.Equals(1)); // OK (true) - changed value should be 1
            Console.WriteLine(unproxiedEntity.Id.Equals(1)); // NOK (false) - expected 1 since  proxiedEntity Id was changed to 1
        }
```

**Comment by jonorossi** [comment]
@dgandini I suspect your `Id` property isn't virtual so DynamicProxy isn't generating an override to `Id` (i.e. `get_Id` and `set_Id` underlying methods) in the `proxiedEntity` which results in the changed identifier getting stored in the class proxy.

**Comment by jonorossi** [comment]
@dgandini your unit test actually seems strange, did you not want the changes to the proxy to pass through to the target? `ProxyUtil.GetUnproxiedInstance` is designed to return the target.

**Comment by jonorossi** [comment]
@dgandini I'm going to close this issue without those questions answered.
