### ISSUE TITLE
Use of APPVEYOR_REPO_TAG_NAME doesn't handle v prefix

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#272]
We've named our git tags in the format `v1.2.3` for quite a while, and is the convention git's documentation, git, linux and many others follow to allow you to easily distingish between `v1.0.0` as a tag and `1.0` which might be your 1.0 series branch off 1.0.0.

I'd like to continue doing this, however the new build set up doesn't permit this. `APPVEYOR_REPO_TAG_NAME` is used 5 times in appveyor.yml and once in common.props.

I'm looking into how to change this now, but feel free to jump in if you've got any suggestions.

/cc @fir3pho3nixx

**Comment by jonorossi** [comment]
Looks like since we are using `Update-AppveyorBuild` we could change over to using `APPVEYOR_BUILD_VERSION` in common.props and strip the "v" in appveyor.yml.

**Comment by fir3pho3nixx** [comment]
Sorry about this, I would just strip it in the appveyor.yml and it should flow through.

**Comment by jonorossi** [comment]
See #273.

**Comment by fir3pho3nixx** [comment]
Will double up your changes on Windsor ... sorry about that.
