### ISSUE TITLE
Castle.Core.Internal.CollectionExtensions

### ISSUE THREAD

**Issue by CeeSharper** [castleproject/Core#276]
Which version did you guys remove the method below from this class? Was it completely deprecated or was it moved? Came across this by accident after upgrading from 3.3.3 to 4.0. Just curious really.

public static void ForEach<T>(this IEnumerable<T> items, Action<T> action);

**Comment by jonorossi** [comment]
@CeeSharper it was removed in 4.0.0. The method was only used once in the Castle Core codebase and is in the "internal" namespace, it really shouldn't have ever been public.

https://github.com/castleproject/Core/commit/c3cfe48ec2da0563ff43f01d454e3342a3e8edf6#diff-d844235c0822c38b984cbf2ae547ca58
