### ISSUE TITLE
DictionaryAdapter notifies at CancelEdit even when SuppressNotifications is used

### ISSUE THREAD

**Issue by Lakritzator** [castleproject/Core#299]
When I call BeginEdit / CancelEdit in a SuppressNotificationsBlock, there are PropertyChanged events for properties that are rolled back.

I wrote tests for this, the test [Test_SuppressNotification_EditCancel](https://github.com/Lakritzator/DictionaryAdapter.CancelEdit.Tests/blob/master/CastleProject.Core.Tests/DictionaryAdapterTests.cs#L80) fails in the last assert.

**Comment by jonorossi** [comment]
@Lakritzator any chance you can dig into DictionaryAdapter and work out what is going wrong?

**Comment by Lakritzator** [comment]
@jonorossi yes, I can do that. I do still first need to finish my work on releasing the new version of [Greenshot](https://getgreenshot.org), but I will try to fix this tomorrow.

**Comment by Lakritzator** [comment]
Added PR #301

**Comment by jonorossi** [comment]
Thanks @Lakritzator, I don't know why it never checked ShouldNotify, I guess this situation was overlooked. Your fix is merged and will be in the next release.

**Comment by Lakritzator** [comment]
You are welcome, never wonder why... happens to all of us. Thanks for merging.
