### ISSUE TITLE
I just upgraded to Castle Core v4.2.0 whilst using Moq v4.7.127 and I am getting an assmbly binding error

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Core#307]
I just upgraded Castle.Core from v4.1.1 to v4.2.0 whilst using Moq and got an assembly binding error. Why is this happening?

**Comment by fir3pho3nixx** [comment]
This is because Castle Core changed the AssemblyVersion attribute to only include major version numbers only so that we can avoid assembly binding errors with future releases/upgrades of Castle Core.  

### Why is the assembly binding error happening then?

This is because Moq have to release a version compiled against the new AssemblyVersion strategy, they are on it! :)

### What do I do in the meantime? I want Castle Core bug fixes.

You can apply this following assembly binding redirect in your App.config.

```
 <dependentAssembly>
    <assemblyIdentity name="Castle.Core" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.0.0.0" />
  </dependentAssembly>
```

### Are you using Castle Core features directly?

If not and you are using the latest version of Visual Studio (15.3.5) then you should probably remove the NuGet reference altogether along with it's assembly bindings. This means Castle Core becomes a `transitive dependency` which you should not have to worry about. 

### Are you guys versioning properly at all?

Yes we are, we just use the AssemblyFileVersion instead. 

![image](https://user-images.githubusercontent.com/607402/31030491-6f672352-a54d-11e7-95d4-5d10b2ad3158.png)

### I am still having issues. 

Please post to this issue and we will try to help you.

**Comment by stakx** [comment]
The more thorough you plan against DLL hell, the more likely it is that NuGet will somehow do everything wrong and land you there anyway... :-)

**Comment by martinRocks** [comment]
I'm having the exactly the same issue, and changed the app.config to the above and it worked for me.

**Comment by stakx** [comment]
@martinRocks - if you update Moq to 4.7.137 as well, you shouldn't need the binding redirect anymore.

**Comment by michelmoorlag** [comment]
I installed Moq 4.7.137 and completely removed the binding redirect for Castle.core from my app.config and that does work indeed.

**Comment by fir3pho3nixx** [comment]
Closing as 4.7.137 has been released.
