### ISSUE TITLE
Interceptor cannot modify captured variable if it is also passed by-ref to intercepted method

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#311]
The following test (running against Castle Core 4.2.0) demonstrates that any code executed during a proxy method interception cannot modify a captured variable if that captured variable was also passed by-ref to the intercepted method:

```csharp
[TestCase(false)] // passes
[TestCase(true)]  // does not pass
public void InterceptorCanModifyCapturedVariable(bool passCapturedVariableByRef)
{
    // Arrange:
    int capturedVariable = 0;
    var interceptor = new Interceptor(invocation =>
    {
        capturedVariable = 1;
    });
    var generator = new ProxyGenerator();
    var voo = generator.CreateInterfaceProxyWithoutTarget<IVoo>(interceptor);

    // Act:
    if (passCapturedVariableByRef)
    {
        voo.Do(ref capturedVariable);
    }
    else
    {
        int otherVariable = 0;
        voo.Do(ref otherVariable);
    }

    // Assert:
    Assert.AreEqual(1, capturedVariable);
}

public interface IVoo
{
    void Do(ref int arg);
}

public class Interceptor : IInterceptor
{
    private Action<IInvocation> callback;

    public Interceptor(Action<IInvocation> callback)
    {
        this.callback = callback;
    }

    public void Intercept(IInvocation invocation)
    {
        this.callback?.Invoke(invocation);
    }
}
```

Contrast this with plain C#, where the same scenario (modifying a captured variable that also gets passed by-ref) works just fine:

```csharp
[Test] // passes
public static void LambdaCanModifyCapturedVariableWhenPassedByRef()
{
    // Arrange:
    int capturedVariable = 0;
    DoAction vooDo = (ref int arg) =>
    {
        capturedVariable = 1;
    }

    // Act:
    vooDo(ref capturedVariable);

    // Assert:
    Assert.AreEqual(1, capturedVariable);
}

delegate void DoAction(ref int x);
```

I suspect this inconsistency is caused by DynamicProxy copying all arguments into an `object[] arguments` array for the `IInvocation` passed to the interceptor, then after the interception, it will copy back values from that array (they might have been modified with `IInvocation.SetArgumentValue`) into all by-ref parameters, effectively overwriting any changes that might have been applied behind DynamicProxy's back to the variable.

The problem here is that the interceptor has no way of knowing that the variable it has captured corresponds to a `ref` parameter, and that it can only change the captured variable by also setting the argument value.

Is there a misunderstanding on my part, or is this a feature, a fixable bug, or a known limitation?

(If it's a bug, and if my above suspicion is more or less correct, then perhaps `IInvocation.SetArgumentValue` should additionally set some "dirty flag" so that only parameters get written back that were actually modified.)

**Comment by jonorossi** [comment]
@stakx good find, sounds like a bug. I don't recall anyone reporting this sort of thing in the past. Were you planning to take a look to propose a fix?

**Comment by stakx** [comment]
@jonorossi - Haven't really thought about it yet, but I'm happy to take a look and see what I can find, I guess it would be a nice challenge... so, yes. :)

**Comment by stakx** [comment]
Closing this issue for the reasons mentioned in #316. Thanks anyway @jonorossi for letting me give this one a try.

**Comment by jonorossi** [comment]
@stakx Thanks for jumping head first into this, you are definitely getting right into DP.

It would be good to get something into the docs about ref parameters though, did you want to add something?

**Comment by stakx** [comment]
I can certainly try. Probably won't have enough time this weekend, but expect a PR sometime next week. :)
