### ISSUE TITLE
Include XML documentation in NuGet package

### ISSUE THREAD

**Issue by dsfranzi** [castleproject/Core#312]
Caste.Core uses docblocks to document (public) methods. Why aren't they included in the latest NuGet package? I'm using version 4.2.0.

**Comment by stakx** [comment]
Good catch. Seems XML documentation was last included with version 4.0.0.

**Comment by fir3pho3nixx** [comment]
Yep, would have been when I reworked the build process. Whoops!

https://github.com/castleproject/Core/pull/313

**Comment by dsfranzi** [comment]
Wow, that was really quick!

Thanks a lot!

**Comment by jonorossi** [comment]
Thanks @fir3pho3nixx, I've updated the changelog. We should get the same change into Windsor.
