### ISSUE TITLE
build problems w/ latest 4.2.1 release

### ISSUE THREAD

**Issue by jaz-ah** [castleproject/Core#317]
When I upgraded the castle.core nuget in my .net solution, I started getting these build errors:

System.TypeInitializationException: The type initializer for 'Moq.Proxy.CastleProxyFactory' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Castle.Core, Version=4.1.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

it looks like the system doesn't like the nuget update that changed the project file from:
<img width="735" alt="screen shot 2017-10-13 at 6 28 43 am" src="https://user-images.githubusercontent.com/13263369/31548486-cee4ccde-afdf-11e7-9ddd-e650179364b6.png">

Any help would be appreciated -thanks!

(Note, I tried changing the reference in the project file manually from 4.0.0.0 to 4.2.1.0 and that didn't help)

**Comment by jonorossi** [comment]
See #307. You need Moq 4.7.137.
