### ISSUE TITLE
The default value for constructor parameters are incorrect when CreateClassProxyTypeWithTarget

### ISSUE THREAD

**Issue by edwardmeng** [castleproject/Core#318]
When implementing constructor injection for the Autofac and other dependency injection libraries with DynamicProxy, we want to create instance with ProxyGenerator.CreateClassProxyWithTarget method. During injection the parameters value should be detected and provided according to reflected default value automatically at runtime. But for the generated proxy type, the relative reflection value for the constructor parameters was incorrect. for example
the original class will be
```cs
public class Sample{
    public Sample(string n, int s = 0){
    }
}
```
then in generated type, 
for the 'n' parameter info.HasDefaultValue will be true, and info.DefaultValue will be null, 
for the 's' parameter info..HasDefaultValue will be true, and info.DefaultValue will be null too.
But in my expectation,
for the 'n' parameter info.HasDefaultValue should be false, and info.DefaultValue should be DbNull or null,
for the 's' parameter info..HasDefaultValue will be true, and info.DefaultValue will be 0.
Please refer to dotnet/corefx#17943 and autofac/Autofac#876

**Comment by jonorossi** [comment]
See #220.

I didn't look at the corefx issue because we also support .NET Framework, but if this is now possible in all cases then we could look at adding this support back.
