### ISSUE TITLE
Castle.Core reference 'broken' since 4.2.0

### ISSUE THREAD

**Issue by SaphuA** [castleproject/Core#320]
I updated Castle.Core and now my DI is broken because the assembly can't be found. I'm pretty sure it's because of the reference changes when adding through nuget.

Before (v4.1.1.0)

```
<Reference Include="Castle.Core, Version=4.1.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc, processorArchitecture=MSIL">
  <HintPath>..\packages\Castle.Core.4.1.1\lib\net45\Castle.Core.dll</HintPath>
</Reference>
```

After (v4.2.1.0)

```
<Reference Include="Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc, processorArchitecture=MSIL">
  <HintPath>..\packages\Castle.Core.4.2.1\lib\net45\Castle.Core.dll</HintPath>
</Reference>
```

Note that it's now referencing Version=4.0.0.0 instead of exact version as expected: Version=4.2.1.0.

**Comment by fir3pho3nixx** [comment]
@SaphuA - We have intentionally done this to avoid assembly binding errors for minor patched versions. 

Please see: https://github.com/castleproject/Core/issues/307
