### ISSUE TITLE
Incorrect assemblyVersion Castle.Core 4.2.1

### ISSUE THREAD

**Issue by Wautvda** [castleproject/Core#325]
With the latest Castle.Core release the Assembly version of the new DLL seems to be incorrect (as can be seen in the attached screenshot). The Assemblyversion of 4.2.1 seems to be 4.0.0.0.

![image](https://user-images.githubusercontent.com/1712579/33329288-803c957a-d45c-11e7-8451-e1e493875556.png)

**Comment by stakx** [comment]
That is intentional, see the changelog, #288 and #307.

**Comment by Wautvda** [comment]
Indeed. I've missed this. Closing this thread.
