### ISSUE TITLE
AssemblyVersion for 4.2.1.0 is set incorrectly to 4.0.0.0

### ISSUE THREAD

**Issue by udlose** [castleproject/Core#338]
I am trying to upgrade from Castle.Core 4.1.1 to 4.2.1.  The upgrade is required as part of upgrading to the latest version of Moq (currently 4.8.2) - which now relies on Castle.Core 4.2.1.0.  I have changed my binding redirects to point from "4.1.1.0" to "4.2.1.0" (as they should be).  However, I'm running into assembly version problems  because of assembly manifest differences.   The problem is that the AssemblyVersion for 4.2.1.0 is marked as "4.0.0.0" in the Assembly Manifest - instead of "4.2.1.0".  

I see that the version 4.1.1 assembly was marked correctly as "4.1.1.0" in the Assembly Manifest.  Was this change on purpose? I assume not...it seems odd that I would have to change my binding redirects from AssemblyVersion 4.1.1.0 to 4.0.0.0 when upgrading...

Manifest for 4.1.1.0:
```
.assembly Castle.Core
{
  ...elided for brevity
  .ver 4:1:1:0
}
.module Castle.Core.dll
// MVID: {58F1BF47-9F7F-411E-8024-AC1DDE1F911B}
```
Manifest for 4.2.1.0:
```
.assembly Castle.Core
{
  ...elided for brevity
  .ver 4:0:0:0
}
.module Castle.Core.dll
// MVID: {3D60A187-5395-41AC-ABE2-15FF220FE659}
```

**Comment by stakx** [comment]
> Was this change on purpose?

Yes. See recent issue #325 and follow links from there.

**Comment by udlose** [comment]
Thank you for your prompt reply and reference to the associated issue!  I'll update my bindings accordingly.
