### ISSUE TITLE
Question: Is it possible to implement Audit Trail via DP?

### ISSUE THREAD

**Issue by fatagun** [castleproject/Core#362]
We are building a large system for a bank and one of the requirement is to Audit Everything!.

That said, is it possible to intercept every object and method, including Controllers and Log everything to a database?

Any examples ? Is this a valid use case? 

Thanks.

**Comment by jonorossi** [comment]
I suggest to start with the DynamicProxy docs to understand what this library can do, it shows examples, describes how the library works and mentions limitations on what types of methods cannot be intercepted.

- https://github.com/castleproject/Core/blob/master/docs/dynamicproxy.md
