### ISSUE TITLE
TypeUtil.ToCSharpString(this Type) does not handle nested generic types correctly

### ISSUE THREAD

**Issue by pmg23** [castleproject/Core#365]
The useful extension method `TypeUtil.ToCSharpString(this Type)` does not correctly deal with types nested within generic types [as of Core 4.2.1]. For example:

```cs
internal class A<T1>
{
    internal class B {}
    internal class C<T2> {}
}

Assert.That(typeof(A<string>.B).ToCSharpString(),
        Is.EqualTo("A<String>.B")); // FAIL: actually "A<·T1·>.B<String>"
Assert.That(typeof(A<string>.C<int>).ToCSharpString(),
        Is.EqualTo("A<String>.C<Int32>")); // FAIL: actually "A<·T1·>.C<String, Int32>"
```

**Comment by stakx** [comment]
(Shameless advertisement:)

Type name formatting is surprisingly complex because there are quite a few corner cases to deal with. I happen to have written a small library recently ([stakx/TypeNameFormatter](https://github.com/stakx/TypeNameFormatter)) that would solve this problem. It's available as a source code NuGet package.

**Comment by stakx** [comment]
That being said, I cannot seem to find a method `TypeUtil.ToCSharpString(this Type)` in Castle Core. Where exactly did you find it?

**Comment by stakx** [comment]
@pmg23, I've migrated this issue over to https://github.com/castleproject/Windsor/issues/404, so please subscribe to the new issue. I'm closing this one here.

**Comment by pmg23** [comment]
Hi @stakx. Thanks for the quick response. I did indeed mean that one from Windsor. (The namespace, which I should have mentioned is `Castle.Core.Internal`, confused me.)

We'll definitely look into using [stakx/TypeNameFormatter](https://github.com/stakx/TypeNameFormatter). Thanks for sharing it.
