### ISSUE TITLE
Castle allows to rewrite read-only parameters (`in` modifier)

### ISSUE THREAD

**Issue by zvirja** [castleproject/Core#369]
Consider the following code sample:

```c#
[Fact]
public void TestProxy()
{
    var proxy = new ProxyGenerator().CreateInterfaceProxyWithoutTarget<IInterfaceWithIn>(new RewritingInterceptor());
    
    var val = new MutableStruct { Value = 24 };
    proxy.DoNotMutate(val);

    Assert.Equal(24, val.Value);
}

public struct MutableStruct
{
    public int Value { get; set; }
}

public interface IInterfaceWithIn
{
    void DoNotMutate(in MutableStruct value);
}

public class RewritingInterceptor : IInterceptor
{
    public void Intercept(IInvocation invocation)
    {
        if (invocation.Method.Name == "DoNotMutate")
        {
            invocation.SetArgumentValue(0, new MutableStruct {Value = 42});
        }
    }
}
```

The issue happens because value is passed by ref, so technically it's possible to rewrite the value. However, like Roslyn, Castle should not allow to rewrite the value via API.

Likely, the fix should be placed somewhere [here](https://github.com/castleproject/Core/blob/39457da1bd1cd835bfca4df8946fb9dcbe996c5e/src/Castle.Core/DynamicProxy/Generators/GeneratorUtil.cs#L25).

/cc: @stakx @blairconrad JFYI as our mock libraries contain tooling for this feature invocation.

**Comment by stakx** [comment]
Yes, this appears to be a problem. I believe we should add a check for `in`-ness of parameters here:

https://github.com/castleproject/Core/blob/39457da1bd1cd835bfca4df8946fb9dcbe996c5e/src/Castle.Core/DynamicProxy/Generators/GeneratorUtil.cs#L38

We could probe whether `(parameters[i].Attributes & ParameterAttributes.In) != 0`, and if so, not write back the argument value.

**Comment by stakx** [comment]
@zvirja - I've had a free afternoon and thought I'd tackle this. You were spot on with where the fix needs to go. :+1:

**Comment by zvirja** [comment]
@jonorossi Could you please release this bug fix on NuGet? At the NSubstitute side I would like to do the following:
- Consume this version as a required to guarantee safety.
- Write unit tests that our generated delegates propagate the `in` modifier correctly. To do that I would like to confirm that value is indeed read-only, but current I cannot write such a test.

I believe it should be fine for `Castle.Core` to publish a bugfix release with increased revision.

Thanks.
