### ISSUE TITLE
`CacheKey` is mutable which can lead to collisions in type cache

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#387]
The following was mentioned by @BrunoJuchli in https://github.com/castleproject/Core/issues/193#issuecomment-398640084 &mdash; it might be good to look into this, possibly in conjunction with #386:

> `CacheKey` is not immutable. Specifically `ProxyGenerationOptions` is mutable. Probably this should not be a problem in this test scenario (since we're using `ProxyGenerationOptions.Default` all the way, aren't we?), but this will, at least, cause other problems:
>
> It's possible to have two `CacheKey`s which are different but later, when they're added to a dictionary, already, make them the same. Imagine:
>
> ```csharp
> var hook1 = new AllMethodsHook();
> var hook2 = new DelegateProxyGenerationHook();
> var options1 = new ProxyGenerationOptions(hook1);
> var options2 = new ProxyGenerationOptions(hook2);
>
> // ---- create a proxy of <IFoo> with options1
> // ---- create a proxy of <IFoo> with options2
>
> options2.Hook = hook1;
> // ---> et voilà, we've got a key collision in the dictionary.
> ```
>
> Now I don't know whether this is just a performance problem (same proxy cached twice) or if it's a more severe problem. Ideally, after building the `ProxyGenerationOptions`, they should be immutable. Also, `CacheKey.GetHashCode` could be computed @ctor (performance optimization, but would also make it clear that it's immutable).

(Minor reformattings by me.)

**Comment by stakx** [comment]
> Ideally, after building the `ProxyGenerationOptions`, they should be immutable.

This doesn't seem feasible. Some of its properties have an interface type (e.g. `IProxyGenerationHook Hook { get; set; }`), so user code is free to provide any implementation; immutability cannot be enforced on DynamicProxy's side.

Documentation to the rescue?

> Also, `CacheKey.GetHashCode` could be computed @ ctor [...]

And at the same time, this typo could be fixed:

https://github.com/castleproject/Core/blob/886e764943ca1be38134f8efac0fe2e0e64e5816/src/Castle.Core/DynamicProxy/Generators/CacheKey.cs#L61

(`+` should be `*`.)

**Comment by BrunoJuchli** [comment]
Making it immutable would mean a breaking interface change.
If we can prove it's causing concurrency issues I'd vote for that.
Documentation generally isn't read, especially not "after the fact" (there might be code out there which is misbehaving).

**Comment by BrunoJuchli** [comment]
Also note the following might be more likely to occur:

    var options = new ProxyGenerationOptions(new AllMethodsHook());

    var allMethodsProxy = *GenerateProxy*(options);

    options.Hook = new DelegateProxyGenerationHook();
    var delegateProxy = *GenerateProxy*(options);

Unexpectedly, the `delegateProxy` will be using the same Hook as `allMethodsProxy`. The second generate will just reuse the cached entry, even though the second call specifies different generation options.

**Comment by BrunoJuchli** [comment]
Option:
To not change the external interface we could take a (immutable) snapshot of `ProxyGenerationOptions` at the external interface and internally use this immutable snapshot.

**Comment by stakx** [comment]
> we could take a snapshot of ProxyGenerationOptions at the external interface and internally use this immutable snapshot.

How would you create an immutable snapshot?

I suspect the best thing we can do is document that users must not modify a `ProxyGenerationOptions` instance once it's been used for proxy creation.

**Comment by stakx** [comment]
You don't have a guarantee that the user-provided `Hook` and `Bar` instances are immutable. You're just making a shallow copy when you'd need a full deep copy.

**Comment by TimLovellSmith** [comment]
If it is mutable you are stuck with it, right? And that could cause real problems if it causes your hashcode to change over time while the object is in a dictionary, since then your key will be in the wrong hash bucket. But I think you would probably just solve this by not using the mutable parts when computing the hashcode

**Comment by jonorossi** [comment]
> But I think you would probably just solve this by not using the mutable parts when computing the hashcode. You can still check the mutable parts when testing equality though.

Yep, and that's what we do with `ProxyGenerationOptions ` including a little something extra for the hook and interceptor selector:

```
var result = Hook != null ? Hook.GetType().GetHashCode() : 0;
result = 29*result + (Selector != null ? 1 : 0);
```

**Comment by stakx** [comment]
Not sure how we should proceed with this. Personally, I have no problem living with the fact that this problem exists, and that we probably cannot do much about it except document it. I'd be fine closing this without taking any action. Does anyone have an objection to that?

**Comment by stakx** [comment]
> We could make [`ProxyGenerationOptions`] "freezable" where once it is used the first time it automatically freezes itself which blocks you mutating it [...].

I have a PR ready that achieves just that, however it belatedly occurred to me that for full correctness, `ProxyGenerationOptions` shouldn't be considered frozen or not frozen on its own; frozeness should be considered in combination with a specific `ProxyGenerator`: freezing an options object is done to preserve the proxy type cache, which is generator-specific.

We could let `ProxyGenerator` keep track of all options objects being passed to it, along with the state they had when first seen. (It might suffice to only record the hash code as a coarse representation of the state.) All options objects being passed in then get screened against that cache, if it is found that their state has since changed, an exception gets thrown.

I'm not sure how this options cache would have to behave with regard to serialization / de-serialization.

I'm also unsure whether or not it's worth all the trouble. I think we could just start with documentation, then re-design towards immutability in vNext.

**Comment by stakx** [comment]
Please forget what I said above. I've been running a few tests and it seems we don't actually have a problem, although I currently fail to understand why. I've been looking at the code that queries the type cache for preexisting keys, and it's rather puzzling:

![dictionary-key-inconsistency](https://user-images.githubusercontent.com/104481/62413383-b2f97100-b60e-11e9-8d9b-ca909baba530.png)

The above shows a situation where we have a `CacheKey` in the type cache dictionary that is equal to `key` (as reported by `CacheKey.GetHashCode` and `CacheKey.Equals`, though not equal by object identity) and yet the call to `.TryGetValue(key, ...)` returns `false`. How come?

**Comment by stakx** [comment]
Ah, the explanation is of course simple, and @TimLovellSmith already hinted at it above: `Dictionary<,>`, being a hash map, obviously uses the hash code of its keys to assign a bin/bucket to the associated value. It uses the hash code computed at the time when the entry gets added. If that hash code later changes, `.TryGetValue` ends up looking in a different bucket and won't find the entry. This has the fortunate effect of mitigating `CacheKey`'s (and along with it, `ProxyGenerationOptions`') mutability. If any `ProxyGenerationOptions` property changes, the hash code will change, and the type cache lookup will not find a match... even though the same `ProxyGenerationOptions` instance was used before. Fortunate for us, but somewhat hard to see through.

I think I've been staring at this problem for too long, what problem are we actually trying to solve? I don't think we actually have a test case demonstrating a specific failure:

* The "key collision in the dictionary" case mentioned in https://github.com/castleproject/Core/issues/387#issue-333976263 would actually be the desired behavior, if two `ProxyGenerationOptions` have the same value, we should end up with the same cache entry.

* The "proxy will unexpectedly use the wrong hook" case mentioned in https://github.com/castleproject/Core/issues/387#issuecomment-398695604 appears to be invalid, since changing an options' object's hook will affect equality, so it cannot lead to DP incorrectly picking another previously generated proxy type from the cache.

Unless I've made a thinking mistake, I think we don't actually have a problem here & can close this issue.

**Comment by BrunoJuchli** [comment]
@stakx 

>Dictionary<,>, being a hash map, obviously uses the hash code of its keys to assign a bin/bucket to the associated value. It uses the hash code computed at the time when the entry gets added. If that hash code later changes, .TryGetValue ends up looking in a different bucket and won't find the entry there.

If [I understand it correctly](http://javabypatel.blogspot.com/2015/10/what-is-load-factor-and-rehashing-in-hashmap.html), there's no guarantee the hashes are different enough for them to be put into a different bucket. But I believe it'll be quite the exception.

The effect would be that Castle.Core could return an earlier generated proxy, which was generated with different options, instead of a new one.

Then again, it's probably quite rare that you'll create a proxy of the same type twice, but with different options.

**Comment by BrunoJuchli** [comment]
@stakx 
Also, hash collisions can occur naturally, even when two objects are not equivalent.
`Dictionary<,>` handles this by using `Equals(..)`, too.

The following will throw a `KeyNotFoundException`, even though the hash value is the same for both keys:

    public class CacheKey
    {
        public override int GetHashCode() => 5564;

        public override bool Equals(object obj) => ReferenceEquals(this, obj);
    }

    public class FooTest
    {
        [Fact]
        public void Collision()
        {
            var dictionary = new Dictionary<CacheKey, string>
            {
                { new CacheKey(), "Foo 1" }
            };

            string value = dictionary[new CacheKey()];
        }
    }

**Comment by BrunoJuchli** [comment]
@stakx 

I don't know about the specific `Dictionary<,>` implementation but If i understand correctly, bucket assignment usually is done like:

    index = hash % array_size

which means two entirely different hashes may end up in the same bucket.

**Comment by stakx** [comment]
> which means two entirely different hashes may end up in the same bucket

... and, as far as I understand it, that's generally unavoidable, unless you use perfect hashing (which would require you to know all keys in advance). But how is this (several values in the same bucket) a problem in this instance?

**Comment by stakx** [comment]
@BrunoJuchli:

> The effect would be that Castle.Core could return an earlier generated proxy, which was generated with different options, instead of a new one.

If I understand you correctly, this would only happen if:

1. a `ProxyGenerationOptions` instance is used to generate a proxy,
2. it is subsequently modified, but its new hash code happens to equal the hash code it would have had before the mutation,
3. it is then used to generate another proxy,
4. the proxy type cache `Dictionary<,>` decides to put the new cache key in the same bucket as the one from (1).

I think I understand now why you suggested taking an immutable snapshot of `ProxyGenerationOptions` (even if the snapshot were only a shallow copy). That would indeed help protecting the proxy type cache from corruption... but like you said, the probability of (1)-(4) happening is perhaps quite low, so I think it sufficient for now to advise users against mutating used `ProxyGenerationOptions`. See my PR.

(But maybe we should improve this someday. I noticed that `CacheKey.GetHashCode` and `ProxyGenerationOptions.GetHashCode` possibly perform too much computational work at present; when it comes down to it, they should favour speed over precision, the latter should be left to `Equals`.)

And a final off-topic tidbit:

> bucket assignment usually is done like:
>
> ```
> index = hash % array_size
> ```

If that kind of stuff interests you, I'd like to recommend to you an article that I read not too long ago: ["Fibonacchi hashing: The optimization that the world forgot (or: a better alternative to integer modulo)" by Malte Skarupke](https://probablydance.com/2018/06/16/fibonacci-hashing-the-optimization-that-the-world-forgot-or-a-better-alternative-to-integer-modulo/). When I read the article I wondered if .NET's `Dictionary<,>` would possibly be faster if it used that approach.

**Comment by BrunoJuchli** [comment]
@stakx 

Almost, just without step 4:

1. a ProxyGenerationOptions instance is used to generate a proxy of `T`,
2. it is subsequently modified, but its new hash code happens to equal the hash code it would have had before the mutation,
3. it is then used to generate another proxy of `T`. Instead of generating a new proxy, the existing proxy of `T` (generated with the old options state) is returned - instead of a new one with the changed `ProxyGenerationOptions`.

---

I also agree with your conclusion (not really worth it to invest a significant amount of time now, documentation should be enough).

---

Note: i first thought it would be enough for `bucketIndex = CacheKey.GetHashCode() % buckets.Length` to match for the issue to arise, but even inside the bucket the hash code is compared for each entry. The relevant code of the dictionary implementation is: https://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,303

**Comment by jonorossi** [comment]
I agree with the conclusion you've come to of looking at immutability in the future but improving documentation now, in practice users haven't reported running into a problem because of this.
