### ISSUE TITLE
Consider `In` modifier when testing whether parameter is read-only

### ISSUE THREAD

**Issue by zvirja** [castleproject/Core#398]
Currently [when testing](https://github.com/castleproject/Core/blob/f84d4fcebdc66b859c321b2eee5434aa41df19f5/src/Castle.Core/DynamicProxy/Generators/GeneratorUtil.cs#L51) a parameter for the immutability we consider the following attributes:
- Parameter attribute flags
- `IsReadOnly` attribute presence.

As it has been discussed [here](https://github.com/castleproject/Core/pull/370#issuecomment-399370350) with @stakx we should additionally test for the required modifier presence to make the logic more robust. The parameter should be considered read-only if __either__:
- parameter attributes has `ParameterAttributes.In` flag _and_ `In` required modifier is present
- parameter attributes has `ParameterAttributes.In` flag _and_ `IsReadOnly` attribute is defined

We should tests the performance and add the quicker check first.

I'd suggest to postpone the improvement till the correct modifier type is clarified here: https://github.com/dotnet/csharplang/issues/1655.

**Comment by stakx** [comment]
@zvirja - we can now proceed with this, the issue over at dotnet/csharplang has been resolved by a merged update to the documentation.
