### ISSUE TITLE
Using Dynamic Proxies on Xamarin iOS 

### ISSUE THREAD

**Issue by ToddThomson** [castleproject/Core#405]
I would like to be able to use Dynamic Proxies in a cross-platform .NetStandard 2 library I use for data access in Xamarin apps. I noticed that System.Reflection.Emit is referenced in Castle.Core which if used would cause grief on the iOS platforrm.

I simply want to create a dynamic proxy to intercept access requests to lazy load a data entity.

**Comment by smartprogrammer93** [comment]
@jonorossi can you please provide a more detailed guide to your approach as it is the only solution to this problem.

**Comment by jonorossi** [comment]
@smartprogrammer93 [Krzysztof has a blog post](https://kozmic.net/2009/08/25/castle-dynamic-proxy-tutorial-part-xiv-persisting-proxies/) from a decade back with more detail and code snippets than I provided, the API still looks like the same.
