### ISSUE TITLE
Codify Caste's coding standards in e.g. .editorconfig?

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#409]
@jonorossi, would you accept a PR that adds some .NET-specific style rules to `.editorconfig`, such that (a) we don't get heaps of unnecessary warnings in VS (see screenshots below), and such that (b) we *do* get additional warnings/errors in VS that we currently might not get?

For example, at the moment my personal VS setup&mdash;using the configuration from *Options* &rarr; *Text Editor* &rarr; *C#* &rarr; *Code Style*&mdash;shows me tons of bad suggestions for reformatting the code:

![without-rules-in-editorconfig](https://user-images.githubusercontent.com/104481/45408661-4fb8c600-b66d-11e8-83ab-a2b1dceed37d.png)

(You've caught me adding superfluous `this.` qualifiers before.)

With certain rules added to `.editorconfig`, this could be changed to this:

![with-rules-in-editorconfig](https://user-images.githubusercontent.com/104481/45408672-56dfd400-b66d-11e8-99e7-ef68b7e9e880.png)

The main rules I have in mind are these (added under the `[*.cs]` section):

```ini
# this makes it an error to omit { } braces for single-statement blocks:
csharp_prefer_braces = true:error

dotnet_sort_system_directives_first = true

# these state that we don't want `this.` qualifiers where not necessary:
dotnet_style_qualification_for_event = false
dotnet_style_qualification_for_field = false
dotnet_style_qualification_for_method = false
dotnet_style_qualification_for_property = false
```

And there's probably a few more. I'd simply try to approximate [Castle's coding standard](https://github.com/castleproject/Home/blob/master/coding-standards.md) as closely as possible given the supported rules (see e.g. documentation on [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) and [this reference by Kent Boogaart](https://kent-boogaart.com/blog/editorconfig-reference-for-c-developers)).

**Comment by jonorossi** [comment]
Sounds great. Yes, would definitely accept a pull request for this.

I assume the error for braces is just an error in the error window, but not actually a blocking error inside the IDE. Just thinking about existing code that doesn't comply.
