### ISSUE TITLE
Change in Mono 5.16 re: reflecting over custom modifiers. How will this affect DynamicProxy?

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#414]
While working on #412 (which upgrades the Travis CI build from Mono 5.10 to 5.16), I noticed that some unit tests related to custom modifiers have started failing ([see build log](https://travis-ci.com/castleproject/Core/jobs/153152926#L2086)).

This breakage was intentionally prepared by @fir3pho3nixx in #287 (thanks!) to notify us of a possible functional change in Mono, so that we'd have a chance to actively review it.

What has changed: Reflection on the newer version of Mono now appears to report custom modifiers placed on parameters when it previously did not see them at all. This is generally beneficial for DynamicProxy. However, Mono reports custom modifiers in the opposite order when compared to the CLR &mdash; we found out about this in https://github.com/castleproject/Core/issues/277#issuecomment-310856930 &mdash; which is what breaks the tests: Both they and DynamicProxy favor the CLR's behavior.

I am opening this issue so we can track any efforts towards figuring out if and how this change will affect DynamicProxy.

**Comment by stakx** [comment]
I've reported these findings to Mono; see https://github.com/mono/mono/issues/11302.

**Comment by stakx** [comment]
The wonderful people over at Mono have already merged a bug fix.

@jonorossi - do you think it's necessary to go further than just waiting for the next Mono update that will include this bug fix? Should DynamicProxy actively try to work around this issue?

I personally don't think that any such effort would pay off, as this bug should only affect C++/CLI scenarios which are probably quite rare&mdash;the .NET compilers currently don't emit more than one cmod per parameter AFAIK so cmod order is not an issue there. I think we can close this issue.

**Comment by jonorossi** [comment]
> The wonderful people over at Mono have already merged a bug fix.

Great to hear.

> do you think it's necessary to go further than just waiting for the next Mono update that will include this bug fix? Should DynamicProxy actively try to work around this issue?

I agree that we should leave things as is, I see no value in us working around it, especially since it'll flip around soon enough.
