### ISSUE TITLE
Proxy on concrete type with constructor arguments

### ISSUE THREAD

**Issue by jaredcnance** [castleproject/Core#420]
Is it possible to create a proxy on a **Type** given the following constraints:

- No target object, just a target type
- The target type can have any constructor, the proxy should also have these constructors and forward the arguments to the target type
- We need to proxy known virtual methods (these could be interface methods, but it shouldn't matter since we have the concrete type)

Specifically, I'm trying to build some abstractions that improve the experience when writing ASP.Net Core integration tests and need to proxy the startup class (reasons documented below). Something like:

```c#
public class TestFixture<TStartup> {
  // ...
  public TestServer CreateTestServer() {
    var startupProxyType = _proxyGenerator
                           .CreateClassProxy(typeof(TStartup), new StartupInterceptor())
                           .GetType();

    var builder = new WebHostBuilder()
                           .UseStartup(startupProxyType);
    // ...
  }
```

I'm creating a proxy instance that isn't really needed just to reference the proxy type. Also, it will fail to create the proxy because the type does not contain a parameter-less constructor.

**Why I'm doing this:**

I need to intercept ASP.Net Core services that get resolved from the container and don't want users to modify their app Startup classes. By proxy-ing the startup class I can get access to the container registrations and transparently add my interceptors.

**Comment by stakx** [comment]
@jaredcnance - In all likelihood, what I am about to suggest is not a supported scenario, and the following solution might no longer work in the next major version of Castle DynamicProxy&mdash;but for now, you might try to build a proxy type as follows:

```csharp
var startupProxyType = proxyGenerator.ProxyBuilder.CreateClassProxyType(typeof(TStartup), Type.EmptyTypes, ProxyGenerationOptions.Default);
```

If you inspect the generated type, you'll see that it has all the constructors of `TStartup`, each of which augmented with an additional first parameter of type `IInterceptor`. (The interceptor instance is not a property of the proxy type, but of the individual proxy.)

**Comment by stakx** [comment]
@jaredcnance, are you still looking for a way to solve the problem you described above, or can we close this?
