### ISSUE TITLE
DictionaryAdapter: Inconistency in NameValueCollection overload behind FEATURE_DICTIONARYADAPTER_XML

### ISSUE THREAD

**Issue by rzontar** [castleproject/Core#422]
The `IDictionaryAdapterFactory` defines 2 overloads of `GetAdapter` that take a `NameValueCollection`. 

In the interface the methods are behind the directive FEATURE_DICTIONARYADAPTER_XML [IDictionaryAdapterFactory.cs#L64](https://github.com/castleproject/Core/blob/ed47d036193a19465286f1703a6963390dd62445/src/Castle.Core/Components.DictionaryAdapter/IDictionaryAdapterFactory.cs#L64). 
But the implementation shields only overloads that `XmlNode` [DictionaryAdapterFactory.cs#L87](https://github.com/castleproject/Core/blob/ed47d036193a19465286f1703a6963390dd62445/src/Castle.Core/Components.DictionaryAdapter/DictionaryAdapterFactory.cs#L87).

Since `System.Collections.Specialized` is already package reference, i think the 2 overloads could be exposed. Otherwise a new FEATURE_DICTIONARYADAPTER_NAMEVALUECOLLECTION could be introduced.

I'm willing to contribute a PR.

**Comment by jonorossi** [comment]
Makes sense, if the implementation can use `NameValueCollection` in .NET Standard then the interface can too. A pull request would be good.

Are you using DictionaryAdapter in your own projects?

**Comment by jonorossi** [comment]
Thanks

**Comment by jonorossi** [comment]
Changelog updated

**Comment by rzontar** [comment]
Glad that worked out so well.

Just to answer your question. Yes, we only use the DictionaryAdapter part of Castle in our project. We are moving to netstandard 2.0 and after migrating a library suddenly the overloads were missing. Apparently, the netstandard 1.5 implementation was picked up. We solved that by multi-targeting to net461.

I would be fantastic if there was netstandard 2.0 build, but i have read the discussion about it in another thread.

Best,
Rok

**Comment by jonorossi** [comment]
We'll have a .NET Standard 2.x build, but as you read in that other thread it can't be 2.0, but 2.1 should be possible.
