### ISSUE TITLE
Documentation falsely claims that each interceptor can only `Proceed` once

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#442]
The [introductory article for DynamicProxy](https://github.com/castleproject/Core/blob/c6354b954fc5f19c345ef19e253eac5f29611772/docs/dynamicproxy-introduction.md#interception-pipeline) currently claims that:

> An interceptor can call `Proceed` at most once, otherwise an exception is thrown.

However, that no longer appears to be true today. [The current implementation of `Proceed`](https://github.com/castleproject/Core/blob/c6354b954fc5f19c345ef19e253eac5f29611772/src/Castle.Core/DynamicProxy/AbstractInvocation.cs#L100-L143) which goes back to https://github.com/castleproject/Core/commit/ea8fa099325d85fb03396be21430cce366aefdf5 allows an interceptor to `Proceed` more than once (in order to be able to implement retry logic).

We should update that part of the documentation.

(I am also uncertain under what circumstances the _"`invocation.Proceed()` has been called more times than expected"_ exception still gets thrown. This could possibly be unreachable code today, but I have yet to check with the unit test suite.)

**Comment by jonorossi** [comment]
> We should update that part of the documentation.

Yep

> (I am also uncertain under what circumstances the _"`invocation.Proceed()` has been called more times than expected"_ exception still gets thrown. This could possibly be unreachable code today, but I have yet to check with the unit test suite.)

Generally it is unreachable code, the exception message still indicates the old behaviour of Proceed-only-once. If the user did something stupid like pass the `IInvocation` to the target and the target called `Proceed` you'd get yourself into the `else if`. I think we should keep the `else if` but change the `InvalidOperationException` to a simple constant message.
