### ISSUE TITLE
Interceptor calling async method before invocation.Proceed()

### ISSUE THREAD

**Issue by naazz** [castleproject/Core#443]
Hi,
 
I am using a framework called Aspnetboilerplate that also use Castle.Core. 

Im trying to create two interceptor that call an async method before invocation.Proceed(). Could not make it work. Everything explained on their repository please refer to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4401
I made a sample reproducing the problem.

Is it possible? Any guidance on how to do that?

Thank you for any further help.

**Comment by naazz** [comment]
Seems to be solved by [https://github.com/castleproject/Core/pull/428](url). Ill closed this issue after confirmation.

**Comment by stakx** [comment]
Hi @naazz. I have only been able to glance over the code you linked to, since it's quite a lot of code. However, it appears that you are experiencing the `Proceed`-after-`await` malfunction. This part of your code might be affected by it:

> ```csharp
> if (method.ReturnType == typeof(Task))
> {
>     returnValue = InternalAsyncHelper.AwaitTaskWithFinally(
>         (Task)returnValue,
>         ex =>
>         {
>             invocation.Proceed();
>         });
> }
> else //Task<TResult>
> {
>     returnValue = InternalAsyncHelper.CallAwaitTaskWithFinallyAndGetResult(
>         method.ReturnType.GenericTypeArguments[0],
>         returnValue,
>         ex =>
>         {
>             invocation.Proceed();
>         });
> }
> ```

Today (coincidence!), we've merged PR #439 which solves that very same problem. In the next Castle.Core release, there will be a new method `IInvocation.CaptureProceedInfo()`. We've also added some new [documentation about async interception](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-async-interception.md) which explains why & how to use that new method.

**Comment by naazz** [comment]
Amen! Thx you i will close this issue and reopen it if needed! 
Any idea for when the next realease is planned?

**Comment by stakx** [comment]
@naazz, I don't know for sure, but @jonorossi usually gets things ready for a new release when enough people are asking for it. :-) We're currently in the process of finalising another few PRs, I would assume that we'd then be ready for [4.4.0 (milestone)](https://github.com/castleproject/Core/milestone/9).

**Comment by xlievo** [comment]
> @naazz，我不确定，但@jonorossi通常会在有足够的人要求时为新版本做好准备。:-)我们目前正在完成另外几个PR，我会假设我们准备好[4.4.0（里程碑）](https://github.com/castleproject/Core/milestone/9)。

I've reconstructed my code in advance through https://ci.appveyor.com/nuget/core-0mhe40ifodk8 to get 0.0.534 version. So far, all the unit tests have passed. 
Thank you!

**Comment by stakx** [comment]
I'll close this issue as it is very likely a solved problem (see above). If you think that's a mistake, please post a brief repro code example so we can reopen.

**Comment by hikalkan** [comment]
Hi all,

This is still not a complete async solution.

It does not work well in some scenarios where the return type is `Task<T>` and we need to execute some other async actions before & after the actual method execution (I want to Process to the target object).

For example, this simple code hangs and does not respond. There were many other scenarios, but this is the simplest one.

````csharp
using System.Threading.Tasks;
using Castle.DynamicProxy;
using Shouldly;
using Xunit;

namespace CastleTests
{
    public class Castle_Interception_Tests
    {
        [Fact]
        public async Task Should_Intercept_Async_Methods()
        {
            var proxyGenerator = new ProxyGenerator();
            var serviceProxy = proxyGenerator.CreateClassProxy<TargetObject>(
                new AsyncInterceptor(),
                new AsyncInterceptor()
                );

            var result = await serviceProxy.GetValueAsync();
            result.ShouldBe(42);
        }
    }

    public class AsyncInterceptor : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            invocation.ReturnValue = InterceptAsync(invocation);
        }

        private async Task<int> InterceptAsync(IInvocation invocation)
        {
            var proceed = invocation.CaptureProceedInfo();

            proceed.Invoke();

            await Task.Delay(1000);

            return await (Task<int>)invocation.ReturnValue;
        }
    }

    public class TargetObject
    {
        public virtual async Task<int> GetValueAsync()
        {
            await Task.Delay(10);
            return 42;
        }
    }
}
````

So, I believe, Castle dynamic proxy should fully support async interceptors. You can even think to introduce `IAsyncInterceptor` with `ProcessAsync()` method to not introduce a breaking change.
