### ISSUE TITLE
Dynamicproxy defaultvalue issue

### ISSUE THREAD

**Issue by hikalkan** [castleproject/Core#45]
Hi,

I've a simple class:

```
public class MyClass
{
    public virtual void MyMethod(string str = null)
    {
        Console.WriteLine(str);
    }
}
```

When I check

```
typeof(MyClass).GetMethod("MyMethod").GetParameters()[0].DefaultValue
```

it's null (as expected). But if I create a dynamicproxy

```
var gen = new ProxyGenerator(new DefaultProxyBuilder());
var proxy = gen.CreateClassProxy<MyClass>();
```

Then I check

proxy.GetType().GetMethod("MyMethod").GetParameters()[0].DefaultValue

It is not null, it is System.Reflection.Missing

This causes a problem when I proxy an ASP.NET MVC Controller with a method which has a default parameter as null such which is defined as:

```
public virtual ActionResult Login(string returnUrl = "/", string loginMessage = null)
```

I use proxy since I want to intercept the method call.

Is this a bug or known situation.

**Comment by stromsky** [comment]
@hikalkan how did you solve this problem? I am experiencing the same problem while using Castle Core 3.3.3.58.

**Comment by hikalkan** [comment]
I had made default value "" (empty string) instead of null. I'm not sure if it works not, since it was a long time ago.

**Comment by stromsky** [comment]
Splendid. Works like a charm. Thanks for turbo fast response.
