### ISSUE TITLE
Add support for [ReadOnly]Span<T> to DynamicProxy

### ISSUE THREAD

**Issue by stakx** [castleproject/Core#453]
DynamicProxy currently does not support proxying methods that use `System.Span<T>` and `System.ReadOnlySpan<T>` in their signature. That is because these types, like all other `ref struct`s, can only live on the stack and therefore cannot be boxed in order to be put into an `IInvocation.Arguments` array.

Given that these two types may become even more widespread in future APIs, I have been wondering whether we might be able to add special support for these to DynamicProxy, now or in v5.

This could possibly work by transparently converting between `[ReadOnly]Span<T>` and `[ReadOnly]Memory<T>` when putting the former into the arguments array, or when reading the latter from there.

That approach might require us to add generic overloads `IInvocation.GetArgumentValue<T>(int index)` and `IInvocation.SetArgumentValue<T>(int index, T value)`. These might be beneficial in the longer term for (1) improved type safety / earlier errors, and (2) possibly less boxing (though not with the current architecture).

This would be an explicit special case. We cannot currently deal with any other `ref struct`, but these two may still be worth it.

Opinions?

**Comment by stakx** [comment]
> [...] might require us to add generic overloads `IInvocation.GetArgumentValue<T>(int index)` and `IInvocation.SetArgumentValue<T>(int index, T value)`.

(P.S. I should probably add that I am not a fan of even more methods to access arguments, so if this would be needed, the whole idea might have to wait for vNextMajor, where we might choose to have generic methods instead of today's non-generic ones.

Even then, there might be dangers: Interceptors that don't expect arguments to have any specific types might use `object` as the generic argument and run into an exception when a `Span<T>` is being fetched (cannot be boxed to `object`). It might be better, after all, to just let interceptors see a `Memory<T>` in place of `Span<T>`.)

**Comment by stakx** [comment]
And apologies again, I appear to have misremembered some facts: While one can "convert" a `Memory<T>` to a `Span<T>` (via pinning), conversions in the opposite direction aren't generally possible without copying memory around (which is precisely what `Span<T>` aims to avoid). It would probably a bad idea if DP copied around possibly large chunks of memory transparently, without the user knowing about it.

So if DP did have some support for `ref struct`s, it would probably have to involve an explicit opt-in, e.g. by requiring client code to provide conversion callback that DP would then involve at the `IInvocation` call boundaries.

For now, I'm closing this issue, as there's no easy immediate solution for supporting `Span<T>` (like I wrongly assumed), and user-provided conversion callbacks would perhaps be a fairly complex new feature. (Not sure I'm quite willing to invest the required time at this moment. :-)

**Comment by jonorossi** [comment]
> And apologies again, I appear to have misremembered some facts [...] It would probably a bad idea if DP copied around possibly large chunks of memory transparently, without the user knowing about it.

When you logged this issue I just thought, hmmm I've got no idea how we are going to make this work 😉. No need to apologise, I've wondered for a while now whether this is something we would have to support somehow, but no one has prompted us yet with a defect.

> For now, I'm closing this issue, as there's no easy immediate solution for supporting `Span<T>` (like I wrongly assumed), and user-provided conversion callbacks would perhaps be a fairly complex new feature. (Not sure I'm quite willing to invest the required time at this moment. :-)

I think that is a good idea, we can wait until someone has a concrete requirement and then try to design an API that would support it.
