### ISSUE TITLE
Creating object with additional properties

### ISSUE THREAD

**Issue by TonyValenti** [castleproject/Core#462]
Hi Castle,
We have a number of objects (in a library we don't control) that we want to "graft" an interface and its supporting properties to.  Can we use Castle to do that?

I'm looking to be able to do something like this:
````
public static T GetData<T>() where T : ThirdPartyObject {

  var MyT = SomeLibrary
      .Create<T>()
      .AddInterface<IContext>()
      ;

  return MyT;
}

public interface IContext {
  public long ContextID {get; set; }
}
````

Can Castle do that?  If so, is there an example I can reference?  If not, is there a library you're aware of that can help?

**Comment by stakx** [comment]
Hi @ToniValenti, yes, proxies can implement additional interfaces. That's what the `additionalInterfacesToProxy` parameter of the various `IProxyGenerator.Create...Proxy...` methods is for.

You can, for example, create a class or interface proxy with a target of type `T`, specify interface `I` in `additionalInterfacesToProxy`, and provide an interceptor that will provide the implementation for members of `I` will forwarding all other member invocations to the `T` target using `invocation.Proceed`.

**Comment by stakx** [comment]
Here's an example:

```csharp
// The type you want to enhance. Must not be sealed:
public class Dog
{
    public void Bark()
    {
        Console.WriteLine("woof");
    }
}

// Defines additional method(s) for the above type:
public interface ISuperdog
{
    void DoBackflip();
}

// Provides the implementations for the above additional method(s):
public class SuperdogInterceptor : IInterceptor
{
    private static MethodInfo doBackflipMethod = typeof(ISuperdog).GetMethod("DoBackflip");

    public void Intercept(IInvocation invocation)
    {
        if (invocation.Method == doBackflipMethod)
        {
            Console.WriteLine("*boink*");
        }
        else
        {
            invocation.Proceed();
        }
    }
}

// Example usage:
var generator = new ProxyGenerator();
var dog = new Dog();
var superdog = generator.CreateClassProxyWithTarget(
    classToProxy: typeof(Dog),
    additionalInterfacesToProxy: new[] { typeof(ISuperdog) },
    target: dog,
    interceptors: new SuperdogInterceptor());

(superdog as Dog).Bark();
(superdog as ISuperdog).DoBackflip();
```

Does this answer your question, @TonyValenti?

**Comment by stakx** [comment]
No news is good news, I assume.
