### ISSUE TITLE
Type matching issues with generic proxy generation methods

### ISSUE THREAD

**Issue by a-ch-chu** [castleproject/Core#470]
I have the following code in a static class:

    private static ProxyGenerator _generator;
    internal static ProxyGenerator Generator
        => _generator = _generator ?? new ProxyGenerator();

    internal static ProxyGenerationOptions Options
        => new ProxyGenerationOptions(/*new BlockReturnProxyGenerationHook()*/);

    internal static ITarget Get<ITarget>(this ITarget e, IInterceptor i)
        => Generator.CreateInterfaceProxyWithTarget<ITarget>(e, Options, i);

I'm receiving the following compiler error on the final line: "Argument 2: cannot convert from 'Castle.DynamicProxy.ProxyGenerationOptions' to 'Castle.DynamicProxy.IInterceptor'".

If I change the final line to the below:
`        => Generator.CreateInterfaceProxyWithTarget<ITarget>(e, i, i);`
I receive the following errors:

- "Argument 2: cannot convert from 'Castle.DynamicProxy.IInterceptor' to 'Castle.DynamicProxy.ProxyGenerationOptions'"

- "Argument 3: cannot convert from 'Castle.DynamicProxy.IInterceptor' to 'Castle.DynamicProxy.IInterceptor'"

The second of these errors is somewhat perplexing, to say the least.

Environment is as follows:

- Castle.Core version 4.4.0

- No other Castle packages installed

- Project is a class library targeting .NET Standard 2.0

- Running on Visual Studio 2019 16.2.3

- The non-generic method works as expected

**Comment by stakx** [comment]
> ```csharp
> internal static ITarget Get<ITarget>(this ITarget e, IInterceptor i)
>   => Generator.CreateInterfaceProxyWithTarget<ITarget>(e, Options, i);
> ```

Invalid syntax can sometimes mislead the Roslyn C# compiler into giving misleading diagnostics. Change the following and watch the problem go away:

```diff
-internal static ITarget Get<ITarget>(this ITarget e, IInterceptor i)
+internal static ITarget Get(this ITarget e, IInterceptor i)
```

:wink:

**Comment by a-ch-chu** [comment]
To be clear, the expression 'ITarget' in the code above is the type variable for the generic method, and is not an extant interface. The change suggested does not compile, giving a "The type or namespace 'ITarget' could not be found" error.

For clarity, I've amended the code fragment above to use a more typical naming scheme:
```cs
private static ProxyGenerator _generator;
internal static ProxyGenerator Generator
    => _generator = _generator ?? new ProxyGenerator();

internal static ProxyGenerationOptions Options
    => new ProxyGenerationOptions(/*new BlockReturnProxyGenerationHook()*/);

internal static ITarget Get<T>(this T e, IInterceptor i)
    => Generator.CreateInterfaceProxyWithTarget<T>(e, Options, i);
```

**Comment by stakx** [comment]
I see! However, my point still stands that this is simply a misleading diagnostic due to a user mistake. Chances are that you are using VS 2019. In VS 2017, you'd get a different, much more helpful error message:

> The type 'ITarget' must be a reference type in order to use it as parameter 'TInterface' in the generic type or method 'ProxyGenerator.CreateInterfaceProxyWithTarget<TInterface>(TInterface, ProxyGenerationOptions, params IInterceptor[])'

So this is the mistake you're making:

```diff
+internal static ITarget Get<ITarget>(this ITarget e, IInterceptor i)
-internal static ITarget Get<ITarget>(this ITarget e, IInterceptor i) where ITarget : class
```

**Comment by a-ch-chu** [comment]
Thanks, that solved the problem - I missed the "where TInterface : class" constraint on the IProxyGenerator interface.
Don't worry, I can definitely see your point re: VS 2019. It's a fairly frustrating and confusing place to have the error message regress. I've reported it as a VS bug as you've suggested.
