### ISSUE TITLE
Changing Invocation Argument values in Async Interceptors

### ISSUE THREAD

**Issue by shoaibshakeel381** [castleproject/Core#476]
I have a use case where I need to change the values of arguments in interceptor. 

Let's assume that I intercepting calls to methods of an interface and my interface is like this:

```cs
public interface IInterceptedContract 
{
  Task DoSomething(out int arg)
}
```

And interceptor logic looks something like this:

```cs
public class Interceptor : IInterceptor
{
  public void Intercept(IInvocation invocation)
  {
    invocation.ReturnValue = asyncMethod(invocation);
  }

  private async Task AsyncMethod(Invocation invocation)
  {
     await Task.Delay(34);
     invocation.SetArgumentValue(index: 0, value: 22);
  }
}
```

This code does not work, `AsyncMethod` actually does update the value in arguments array, but the caller only see the default value which is `0`. 

Can somebody explain the reasoning behind this behavior and is there a better/alternative way to achieve this?

One thing to note is that if I convert this code to a synchronous one, then everything works as expected. Also I am aware that we cannot use out,ref or in parameters in Async methods.

**Comment by jonorossi** [comment]
I recommend reading our docs on async, especially the "Intercepting awaitable methods that produce a return value" section.

> In other words, the very first await inside your interceptor completes the proxy method interception!
> (https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-async-interception.md)

**Comment by shoaibshakeel381** [comment]
I've read the docs but cannot find anything regarding changing arguments values.

**Comment by jonorossi** [comment]
> I've read the docs but cannot find anything regarding changing arguments values.

DynamicProxy interception is complete when the `Task` return value is returned from the first await, the "Closing remarks" on that page talks about `SetArgumentValue` and stale invocation objects being modified after interception.

The [Behavior of by-reference parameters during interception](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-by-ref-parameters.md) docs page talks about how by-ref arguments are returned to calling code by DynamicProxy.

**Comment by shoaibshakeel381** [comment]
i understand. thanks.
