### ISSUE TITLE
Named arguments on IInvocation

### ISSUE THREAD

**Issue by jstafford5380** [castleproject/Core#481]
I noticed that the arguments are provided on the IInvocation object but they are not named, so I don't know which values belong to which arguments on the method. Are these available somewhere else? If not, I'd like to request they be added.

**Comment by stakx** [comment]
You can find out the parameter names via `invocation.Method.GetParameters()`; those will be in the same order as `invocation.Arguments`, so you can build your own dictionary mapping from parameter names to parameter/argument index.

DynamicProxy does not do that for you for performance reasons, I assume. 

(Performance could perhaps be taken care of by caching the name-to-index maps per `MethodInfo` after building it once, but it might not be worth adding that memory pressure for a feature that a majority of users might not strictly need. I suggest you add this feature in your own code base, via extension methods on `IInvocation`.)

**Comment by jstafford5380** [comment]
Yeah that's what I have implemented at the moment, it just feels a bit hacky and it's generally not good practice to rely on ordering in an unordered set. I haven't looked to see how the arguments are extracted, but I supposed offering some lazy loaded list could help with performance.

**Comment by stakx** [comment]
> [...] to rely on ordering in an unordered set [...]

A method's parameter list is not an unordered set!

**Comment by jstafford5380** [comment]
> > [...] to rely on ordering in an unordered set [...]
> 
> A method's parameter list is not an unordered set!

No not the Method, but I have to assume that the `object[]` could be!

**Comment by stakx** [comment]
@jstafford5380, again, no. Both `invocation.Arguments` and `invocation.Method.GetParameters()` are in the same order. .NET uses a calling convention where arguments are pushed onto the evaluation stack from left to right, and they end up in `invocation.Arguments` in the same order. `invocation.Arguments[0]` corresponds to the left-most argument, while `invocation.Method.GetParameters[0]` corresponds to the left-most parameter. They match up nicely by index.

About the only mapping logic DP applies is to skip the `this` argument (accessed through `ldarg.0` in IL) to ensure `invocation.Arguments` matches up 1:1 with `invocation.Method.GetParameters` without any off-by-1 index shift.

But don't take my word for it; you can check with the CLI specification (ECMA-335) and DynamicProxy's source code.

(There *might* possibly be some very rare interop edge cases where different calling conventions are involved; or possibly some delegate related edge cases where the first argument gets explicitly bound and the argument list is shifted to index 1, but that's just a guess; I don't think I've ever actually observed such a case.)

**Comment by jstafford5380** [comment]
ok thanks
