### ISSUE TITLE
Question: How to implement Dynamic Lazy Proxy the right way

### ISSUE THREAD

**Issue by thoros1179** [castleproject/Core#490]
Hi there,

I hope somebody can help me or at least point in the right direction.

We have a large business application and have some custom logic for lazy registration and resolution of dependencies. This works all very well with Castle if we inject `Lazy<T>` into our classes (instead of [LazyEx](https://github.com/castleproject/Windsor/blob/6900bbf4f7ece81ee2987238f8eba59bd650642b/src/Castle.Windsor/MicroKernel/Internal/LazyEx.cs) we have an own implementation for that, which is registered to the container).

Now we want to experiment with using this feature implicitly, even if there isn´t explcitly injected Lazy<T>. 

Just to be clear some simple code of what I want to achieve:

This:

    internal class MyClass : IMyClass
    {
        public MyClass(IMyOtherClass dependency)
        {
            Dependency = dependency;
        }

        private IMyOtherClass Dependency { get; set; }

        public void DoStuff()
        {
            Dependency.DoStuff();
        }
    }

should internally (under the hood) behave like this

    internal class MyClass : IMyClass
    {
        public MyClass(Lazy<IMyOtherClass> dependency)
        {
            Dependency = dependency;
        }
        private Lazy<IMyOtherClass> Dependency { get; set; }

        public void DoStuff()
        {
            Dependency.Value.DoStuff();
        }
    }

I´ve looked through many examples of dynamic interface proxy with target but still have no clue how to achieve this special requirement, especially because it has to be a generic solution working for all registered interfaces (and classes if possible). Maybe someone could point me in the right direction?

**Comment by stakx** [comment]
I'm not currently near any computer so ai cannot provide any code, but here's an idea: IIRC, for some proxy types it is possible to change the target object during interception (using [this method](https://github.com/castleproject/Core/blob/6819f5c7373231589d692c874a7b41b2ec0b49e3/src/Castle.Core/DynamicProxy/IProxyTargetAccessor.cs#L28-L31)). So what you could do is to instantiate the lazy object during interception (if it hasn't happened already during an earlier invocation), set it as the proxy's target, then `.Proceed` the invocation to the target.

**Comment by thoros1179** [comment]
> I'm not currently near any computer so I cannot provide any code, but here's an idea: IIRC, for some proxy types it is possible to change the target object during interception (using [this method](https://github.com/castleproject/Core/blob/6819f5c7373231589d692c874a7b41b2ec0b49e3/src/Castle.Core/DynamicProxy/IProxyTargetAccessor.cs#L28-L32)). So what you could do is to instantiate the lazy object during interception (if it hasn't happened already during an earlier invocation), set it as the proxy's target, then `.Proceed` the invocation to the target.

Thanks for your suggestion.
First thing is: the instantiation of the lazy object would have to be done by the container, as there is be a whole dependency tree beneath, so cannot be done manually.
Second thing: I couldn´t just proceed the method invocations to the new target, because I would have to insert a ".Value" (it´s a lazy object after all) into the method-calls. Reflecting them would probably work but may be a bit slow.

I´ll try putting it together this way and see how it works, but what I´m already sensing from your answer is that there´s no straightforward way to do this (which I just didn´t see), am I right?

**Comment by stakx** [comment]
> First thing is: the instantiation of the lazy object would have to be done by the container, as there is a whole dependency tree beneath, so cannot be done manually.

Then make the container available by injecting it into your interceptor.

> Second thing: I couldn´t just proceed the method invocations to the new target, because I would have to insert a ".Value" (it´s a lazy object after all) into the method-calls.

You'd no longer need to use `Lazy<>`, since your proxy now takes over its function. If your interceptor creates the target object (what would otherwise have been the `Lazy<>.Value`) in `Intercept` that means creation of the target becomes lazy because it only happens on the first method call. The outside world however will not see a `Lazy<>` but your proxy, which has the same type as the target.

**Comment by stakx** [comment]
See the previous issue https://github.com/castleproject/Core/issues/293 for an example how to implement this. Basically:

```csharp
class LazyInterceptor<TTarget> : IInterceptor
{
    private readonly Lazy<TTarget> target;

    public LazyInterceptor(Lazy<TTarget> target)
    {
        this.target = target;
    }

    public void Intercept(IInvocation invocation)
    {
        if (invocation.InvocationTarget == null)
        {
            ((IProxyTargetAccessor)invocation.Proxy).DynProxySetTarget(this.target.Value);
            ((IChangeProxyTarget)invocation).ChangeInvocationTarget(this.target.Value);
        }

        invocation.Proceed();
    }
}

proxyGenerator.CreateInterfaceProxyWithTargetInterface<IService>(
    target: null,
    interceptors: new LazyInterceptor<IService>(new Lazy<IService>(() => new ConcreteService()))); 
```

**Comment by thoros1179** [comment]
Thanks for your suggestion. But the last part is bugging me... there is no explicit place where I can call the ProxyGenerator. The **IService** interface is injected into some class, which is resolved by the container. The creation of the proxy must happen implicitly, so I need to somehow tell the container to dynamically create an interface-proxy, if an interface is injected into some class. And that´s where I´m stuck.

**Comment by stakx** [comment]
How you configure your DI container is a totally different problem, and since DynamicProxy ian't itself a DI container you're perhaps asking in the wrong place.

At a high level, it seems that you'd want to configure your DI container like this:

```csharp
container
.Resolve<IService>()
.As(() => proxyGenerator.CreateInterfaceProxyWithTargetInterface<IService>(
    target: null,
    interceptors: new LazyInterceptor<ITarget>(
        new Lazy<IService>(
            () => new ServiceImpl(...)))));
```

If you want to instantiate `ServiceImpl` by requesting an `IService` from your container, you will need a way to tell your container to use a different eegistration, or you'll just get a lazy `IService` again.

How exactly you configure your container is a question for the folks that offer support for that container.

**Comment by stakx** [comment]
@thoros1179 is there anything else for us to do (or help with) here? Or should we close this issue?

**Comment by thoros1179** [comment]
Sorry for the delay. The Interceptor you provided basically works for what I want it to. As you said my remaining problem now is with my container to resolve the inner content of it. I got it working already but still have some side effects to tackle. So basically this can be closed, muchos gracias!
