### ISSUE TITLE
question: difference CreateClassProxyType vs CreateClassProxyTypeWithTarget

### ISSUE THREAD

**Issue by WeihanLi** [castleproject/Core#499]
what's the difference `CreateClassProxyType` and `CreateClassProxyTypeWithTarget`

**Comment by jonorossi** [comment]
Please read the docs: https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-kinds-of-proxy-objects.md

**Comment by WeihanLi** [comment]
Thanks @jonorossi
