### ISSUE TITLE
Castle.Core-log4net update problem

### ISSUE THREAD

**Issue by hikalkan** [castleproject/Core#52]
Hi,

I use Castle Windsor and Log4Net. I updated nuget package Castle.Core-log4net to v3.3.0 (latest). Then I got an error.

Exception: 
Could not convert string 'Castle.Services.Logging.Log4netIntegration.Log4netFactory,Castle.Services.Logging.Log4netIntegration,Version=3.2.0.0, Culture=neutral,PublicKeyToken=407dd0808d44fbdc' to a type.

Inner Exception:
Could not load file or assembly 'Castle.Services.Logging.Log4netIntegration, Version=3.2.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Castle.Services.Logging.Log4netIntegration, Version=3.2.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc

I think Castle.Windsor-log4net package does not work with this new Castle.Core-log4net version. As I see, Castle.Core-log4net package is pretty old.

Can you update it? Also, It would be nice to work with Log4Net's latest version.

Thank you.

**Comment by jeanjmnez** [comment]
Hi, i'm having the same exacti issue, and the proposed solutions did not work, any other idea?

**Comment by ssolomon** [comment]
I was having the same issue, and the binding redirects above did not work.  After taking a look at the version number of the Castle.Services.Logging.Log4netIntegration dll, it noticed it was version 3.2.0.0.  So it tried the following and it worked.  I find it very odd how they won't upgrade this thing.

`<dependentAssembly>
        <assemblyIdentity name="Castle.Services.Logging.Log4netIntegration" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>`<dependentAssembly>
        <assemblyIdentity name="Castle.Services.Logging.Log4netIntegration" publicKeyToken="407dd0808d44fbdc" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.2.0.0" />
      </dependentAssembly>

**Comment by jonorossi** [comment]
> I find it very odd how they won't upgrade this thing.

@ssolomon this is a closed issue last active nearly a year ago, if you are having a problem please log a new issue with some reproduction steps. The [Castle.Core-log4net 3.3.3](https://www.nuget.org/packages/Castle.Core-log4net/3.3.3) package was shipped in November 2014 after this issue was created and closed.
