### ISSUE TITLE
Castle Core dependencies for .Net Standard 1.5

### ISSUE THREAD

**Issue by stcallan** [castleproject/Core#534]
Does Castle.Core have any dependencies on .Net Standard 2.0 ? 

We can see there are dependencies for .Net Standard 1.5

Just looking at this here:
![image](https://user-images.githubusercontent.com/31473371/90893640-425af900-e3b7-11ea-8018-24f9ad7fd683.png)

Thanks!

**Comment by SonnyCampbellUnity** [comment]
Thanks guys
