### ISSUE TITLE
Generate proxy without IInterceptor ctor args

### ISSUE THREAD

**Issue by superstator** [castleproject/Core#537]
I'd like to use `DynamicProxy` to create a proxy for an abstract type, adding an attribute but without actually adding any interceptors and without changing the constructors. I can do most of this already - for example, if I have a class:

```
    public abstract class Class1
    {
        public Class1(string name)
        {
            Name = name;
        }

        public string Name { get; private set; }
    }
```

and an extension method:

```
        public static object GetCastleProxy(this Type type)
        {
            var gen = new DefaultProxyBuilder();
            var opt = new ProxyGenerationOptions();
            opt.AdditionalAttributes.Add(CustomAttributeInfo.FromExpression(() => new SerializableAttribute()));
            return gen.CreateClassProxyType(type, new Type[0], opt).Assembly;
        }
```

I can generate an assembly and create an instance:

```
       [Fact]
        public void CanGetCastleProxy()
        {
            var assm = typeof(Class1).GetCastleProxy() as System.Reflection.Assembly;
            var obj = Activator.CreateInstance(assm.GetTypes()[0], new Castle.DynamicProxy.IInterceptor[0], "foo");
            Assert.IsAssignableFrom<Class1>(obj);
            Assert.Equal("foo", ((Class1)obj).Name);
            Assert.Collection(obj.GetType().GetCustomAttributes(true), a => Assert.IsType<SerializableAttribute>(a));
        }
```

The only catch is that I need to pass that empty `IInterceptor` array during activation. Looking at the code in Castle.Core/DynamicProxy/ClassProxyGenerator.cs, I don't see a way to skip the addition of those ctor args. Is there another way to achieve this? Would it be a huge change to add a flag in `ProxyGenerationOptions` to skip the interceptor args?

**Comment by stakx** [comment]
What would be the use case here? Why create a proxy at all if you're not interested in using its core feature, method interception?

**Comment by jonorossi** [comment]
I agree with @stakx, what is the use case here.

Your DynamicProxy's entry point should be to a `ProxyGenerator` not a `DefaultProxyBuilder`, you should be letting DynamicProxy instantiate your proxy object, not assuming what the constructor arguments will be.

**Comment by superstator** [comment]
Fair questions! The use case is really just adding attributes to a class at runtime, and then passing the dynamically generated assembly to another process. That other process will use standard dependency injection mechanisms to create its own instances. That’s also why I’m skipping ProxyGenerator, since at this point I’m really just interested in the generated type and containing assembly.

**Comment by stakx** [comment]
I see. DynamicProxy may be convenient because it does 90% of what you want; but it it is also overkill because it does many more things that you _don't_ need (like overriding methods, creating those ctors, etc.). For this reason, I suspect you might be better off without DynamicProxy.

It shouldn't be too difficult using System.Reflection.Emit directly to emit a class with a specific `BaseClass` into your own dynamic assembly. Adding a single attribute also isn't that hard. The hardest part might be to replicate the base class' attributes correctly. (For example, you may want to replicate those that aren't `Inherit`-ed.)

**Comment by superstator** [comment]
I started down that road, but couldn't quite make it work. As you say, creating the new class and adding attributes is easy, but cloning the constructors stumped me, and I have no idea what else I haven't considered. I have no doubt it can be done, and I could probably use the bits of DynamicProxy that I need as a template to get it working, but then I'm on the hook maintaining a bunch of Reflection.Emit code that I barely understand. I can see why you'd be reluctant to add a feature or take a PR with such a narrow use case, but if you never ask the answer is always no...

**Comment by superstator** [comment]
I think I finally cracked the nut on doing constructor generation myself, thanks to [this](https://stackoverflow.com/questions/6879279/using-typebuilder-to-create-a-pass-through-constructor-for-the-base-class) so I guess this is moot. Thanks for humoring me anyway!
