### ISSUE TITLE
I cannot find artifacts for 4.4.1 in appveyor

### ISSUE THREAD

**Issue by marlonedu** [castleproject/Core#558]
Hello. I want to load the symbols from version 4.4.1 but I can't find its artifacts. I have searched here https://ci.appveyor.com/project/castleproject/core/build/4.4.1/artifacts but I haven't found it.

**Comment by stakx** [comment]
You have looked in the right place. I suppose the reason that the symbols are no longer there is AppVeyor's current artifacts retention policy (introduced about 2 years ago, IIRC), which states that build artifacts will be deleted after 6 months. 

That's unfortunate, and something we should keep in mind when migrating our CI from AppVeyor to GitHub Actions (#497).

**Comment by marlonedu** [comment]
1. But the artifacts from version 4.4.0, which I understand are older than 4.4.1, can be viewed on AppVeyor :/
2. So are you planning to migrate to GitHub Actions? If that is the case, when you do this migration, do not forget to put it in the documentation please.

**Comment by stakx** [comment]
> But the artifacts from version 4.4.0, which I understand are older than 4.4.1, can be viewed on AppVeyor :/

I suspect those are still around because the build ran before the new artifact retention policy was introduced.

> So are you planning to migrate to GitHub Actions?

Yes, that's the plan.

> If that is the case, when you do this migration, do not forget to put it in the documentation please.

Sure.

**Comment by marlonedu** [comment]
> I suspect those are still around because the build ran before the new artifact retention policy was introduced.
Ok, so that's what surely happened.

Great, thank you for the answers 👍

**Comment by jonorossi** [comment]
We should stop relying on symbols being available for releases on our CI server and instead publish symbols with NuGet now that there is a better story for symbols.
