### ISSUE TITLE
better readme

### ISSUE THREAD

**Issue by kkozmic** [castleproject/Core#56]
We need readme that's more useful than the one we have now.

A few ideas

- [x] Put our logo
- [x] Tweet-long description of what this project is
- [ ] Simple code examples
   - [ ] for DynamicProxy
   - [ ] for DictionaryAdapter
- [x] Important links

**Comment by jonorossi** [comment]
@kkozmic I put our logo, a short description and important links into the README the a few weeks ago with the migration of docs from STW.

I didn't put code examples into the README, do you still want that for Castle Core? I think it makes sense for Windsor, but less so for Castle Core.

**Comment by kkozmic** [comment]
yeah, I'm happy either way

**Comment by jonorossi** [comment]
Cool, lets close this one then. We can just make incremental changes directly now.
