### ISSUE TITLE
Please change Password to Keyword or fix xml

### ISSUE THREAD

**Issue by foxjazz** [castleproject/Core#586]
Security issue with name of Password which appears after nuget install on the castle core xml.
Trying to get this to be either removed or name changed.

**Comment by jonorossi** [comment]
@foxjazz I don't understand your request. Do we have a security issue? If you wish to disclose something privately rather than here you can email me directly at `jono` at my GitHub username `.com`.

**Comment by jonorossi** [comment]
@foxjazz I've not received a response from you, closing this issue.
