### ISSUE TITLE
Support for contructor args in proxy base type

### ISSUE THREAD

**Issue by p33t** [castleproject/Core#587]
It would be useful to allow proxy classes to supply constructor args to a base type.  The args could be supplied explicitly in `ProxyGenerationOptions`.  E.g.
`ProxyGenerationOptions.BaseTypeConstructorArgs(params object[] args)`

This would have allowed me to use `ProxyGenerator.CreateInterfaceProxyWithoutTarget()` and `ProxyGenerationOptions.BaseTypeForInterfaceProxy` with ServiceFabric [StatelessService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.runtime.statelessservice?view=azure-dotnet). (We didn't want to put in hacks to work around, like placing the constructor arg momentarily in a static variable)

**Comment by stakx** [comment]
@p33t, sorry for the late reply. It didn't occur to me until now that you might simply turn things around and, instead of creating an interface proxy with a specific base class, create a class proxy implementing an additional interface. That way, you could provide ctor arguments.

**Comment by stakx** [comment]
Do you think this alternative solution would be sufficient? If so, then there's no need to enhance DynamicProxy's API, and we can close this.

**Comment by p33t** [comment]
@stakx , thanks for reply. I've moved onto another project which doesn't use ServiceFabric so I don't need this feature any more.
I'll remember your tip about creating a class proxy instead in future!
