### ISSUE TITLE
Memory Leak in DictionaryAdapterFactory.cs::CreateTypeBuilder() method

### ISSUE THREAD

**Issue by RodneyDavies** [castleproject/Core#59]
Hi,

Under namespace Castle.Components.DictionaryAdapter, DictionaryAdapterFactory.cs - 

private static TypeBuilder CreateTypeBuilder(Type type, AppDomain appDomain) 

There is a memory leak on this line - 

var assemblyBuilder = appDomain.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.Run); 

It should be  -

var assemblyBuilder = appDomain.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.RunAndCollect);

Can you please correct this? 

You may also wish to check all other instances of the use of AssemblyBuilderAccess.Run and perhaps change them to AssemblyBuilderAccess.RunAndCollect?

Thanks,
Rodney

**Comment by kkozmic** [comment]
Hey,

Is this OK to close now?

**Comment by jonorossi** [comment]
If this is something that still interests you let us know, but since this has stalled and been inactive since early 2014 I'm going to close it for now.
