### ISSUE TITLE
How to identify in the interceptor when the keyword "await" was used

### ISSUE THREAD

**Issue by rodrigoreis** [castleproject/Core#599]
Is there a way to identify in the interceptor when the keyword "await" was used when calling a method of a proxied class?

**Comment by stakx** [comment]
> identify in the interceptor

What exactly do you mean by that?

**Comment by rodrigoreis** [comment]
When I create a proxy for a class that contains a method that returns TASK or TASK<T>, I would like to know if at the moment the interceptor acts, if the user called this method using the await keyword or not.

```
// this approach should materialize the result.
var resultUsingAwait = await obj.MethodAsync();

// this approach should only return a TASK
var result = obj.MethodAsync();
```

**Comment by stakx** [comment]
This is not possible. `async`/`await` are a C# language construct that does not exist at the runtime / IL bytecode level; code that uses those keywords is transformed by the compiler into more basic code patterns (here: a state machine), a process that the .NET compiler folks refer to as "lowering".

There are a bunch of other C# language features that only exist in source code, but disappear in the compiled IL bytecode, e.g. `foreach` loops, `using` statements, or `lock`s, to mention just a few.

I suggest you compile some `async`/`await` code and open the resulting assembly in a tool such as ILSpy or ILDASM, and you'll see for yourself that you'll find no more `await`s.
