### ISSUE TITLE
Castle.Core 4.4.2 add new target frameworks

### ISSUE THREAD

**Issue by Havunen** [castleproject/Core#606]
Hi,

This is feature request to deploy new version of castle core to nuget by just adding modern compilation targets to this library.

netstandard2.0, netstandard2.1, net5.0, net6
0

And remove dependencies from those targets like it was done for .net framework 4.0 and 4.5

This way modern applications dont get those old libraries installed.

Keep the old targets there then this is not breaking change

**Comment by Havunen** [comment]
Because I couldn't find any fix to this I released my own version of NSubstitute and Castle.Core to nuget which target only .NET 5 and .NET 6 code.
They are available in: https://www.nuget.org/packages/NSubstituteNet6/   and https://www.nuget.org/packages/CastleCoreNet6/

**Comment by IanKemp** [comment]
netstandard2.0 and netstandard2.1 are already targeted, unfortunately there is no NuGet package released with those targets :(

**Comment by Havunen** [comment]
yep, indeed

**Comment by jonorossi** [comment]
Closing. Please follow #613.
