### ISSUE TITLE
Add new target frameworks - release new nuget package

### ISSUE THREAD

**Issue by leolplex** [castleproject/Core#609]
@jonorossi 

As #606 added support .netstandard2.0;netstandard2.1 but last nuget packages does not have this change. 

Could you release a new nuget version with this change?

This change resolved the next vulnerability: 
https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708

**Comment by IanKemp** [comment]
> @jonorossi
> 
> As #606 added support .netstandard2.0;netstandard2.1 but last nuget packages does not have this change.
> 
> Could you release a new nuget version with this change?
> 
> This change resolved the next vulnerability: https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTREGULAREXPRESSIONS-174708

I don't think you read #606. It's a **feature request** to add those new targets.

**Comment by IanKemp** [comment]
To be clear: #606 **did not add support for anything**, it is a feature request to add support for net5.0 and net6 targets.

netstandard2.0 and netstandard2.1 have been targeted since 16 May 2020... but the last version of this package published was done so on 6 May 2020.

**Comment by jonorossi** [comment]
Closing. Please follow #613.

**Comment by leolplex** [comment]
> To be clear: #606 **did not add support for anything**, it is a feature request to add support for net5.0 and net6 targets.
> 
> netstandard2.0 and netstandard2.1 have been targeted [since 16 May 2020](https://github.com/castleproject/Core/commits/master/src/Castle.Core/Castle.Core.csproj)... but the last version of this package published was done so on 6 May 2020.

You're right!

**Comment by leolplex** [comment]
> Closing. Please follow #613.

Thanks 👍
