### ISSUE TITLE
Error when trying to update to Castle.Core 5.0

### ISSUE THREAD

**Issue by cezar-pimentel** [castleproject/Core#628]
When I try to update my Castle.Core package in nuget, I receive this error:

Unable to resolve dependencies. 'Castle.Core 5.0.0' is not compatible with 'Castle.Windsor 5.1.2 constraint: Castle.Core (>= 4.4.1 && < 5.0.0)'.				

Is this constraint correct? Could someone explain to me why this constraint exist?

Thanks in advance

![image](https://user-images.githubusercontent.com/12258489/170397365-649d7cb2-9fba-4eb2-b5ef-65e658001601.png)

Update: I forgot to mention. I'm trying to update it on a .NET Framework 4.8 project.

**Comment by jonorossi** [comment]
> Is this constraint correct?

Yes. Castle Windsor does not yet support Castle Core 5.0.

Follow the Castle Windsor issue over there: https://github.com/castleproject/Windsor/issues/612

**Comment by cezar-pimentel** [comment]
Ok! Thanks for the explanation and for your time!
Cheers!

👊
