### ISSUE TITLE
Proxy exception handling logic skipped when invoked from AspNetCore Project

### ISSUE THREAD

**Issue by TarekAljabban** [castleproject/Core#629]
I'm using a Castle proxy that looks like the following:

```
public class CastleInterceptor : IInterceptor
    {
        private readonly ILogger _logger;

        public CastleInterceptor(ILogger logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public void Intercept(IInvocation invocation)
        {
            if (invocation == null)
            {
                throw new ArgumentNullException(nameof(invocation));
            }

            if (IsAsyncMethod(invocation.Method))
            {
                InterceptAsyncMethod(invocation);
            }
        }

        private void InterceptAsyncMethod(IInvocation invocation)
        {
            try
            {
                invocation.Proceed();

                invocation.ReturnValue = InterceptAsync((dynamic)invocation.ReturnValue);
            }
            catch (Exception ex)
            {
                HandleException(ex);
            }
            finally
            {
                _logger.Information("Final block");
            }
        }

        private async Task InterceptAsync(Task task)
        {
            await task;
        }

        private async Task<T> InterceptAsync<T>(Task<T> task)
        {
            T result = await task;
            return result;
        }

        private static bool IsAsyncMethod(MethodInfo method)
        {
            return method.ReturnType == typeof(Task) ||
                (method.ReturnType.IsGenericType && method.ReturnType.GetGenericTypeDefinition() == typeof(Task<>));
        }
    }
```

When testing this proxy using a unit test, everything is working as expected, including the exception handling logic. As in, when the underlying target method throws an exception, this exception is caught by the interceptors "Catch" block and the `HandleException(ex);` call is made as expected.

However, when I'm using this proxy in an AspNetCore project, the interception logic still works but the exception handling logic is no longer invoked. It seems that for some reason that `invocation.Proceed();` starts swallowing any thrown exceptions.

The proxy object is added to IServiceCollection using the following extension method:

```
public static void AddSingletonWithProxy<TInterface, TImplementation>(this IServiceCollection services)
            where TInterface : class
            where TImplementation : class, TInterface
        {
            services.AddSingleton<TImplementation>();
            services.AddSingleton(new ProxyGenerator());
            services.AddSingleton<IInterceptor, CastleInterceptor>();

            services.AddSingleton(typeof(TInterface), serviceProvider =>
            {
                var proxyGenerator = serviceProvider.GetRequiredService<ProxyGenerator>();
                var actual = serviceProvider.GetRequiredService<TImplementation>();
                var interceptors = serviceProvider.GetServices<IInterceptor>().ToArray();
                return proxyGenerator.CreateInterfaceProxyWithTarget(typeof(TInterface), actual, interceptors);
            });
        }
```

Please let me know what you think of this, and whether you think it's a bug from Castle side or something I'm doing incorrectly.

**Comment by stakx** [comment]
Looks like a problem in yoir own code. If you want your interceptor to catch exceptions that may be thrown by an async method, then you need to await that method's result inside the `try` block (i.e. you'd need to `await` the `Task` returned by `InterceptAsync`). Otherwise you end up with a race between your interceptor and the task. If the task fails with an exception after your interceptor has left the `try` block, you end up with a swallowed / unhandled exception.

**Comment by stakx** [comment]
I forgot to mention, the interception pipeline of proxies generated by DynamicProxy are purely synchronous code and not completely thread-safe (the `invocation.Proceed()` method is especially unsafe). This can render async/await operations inside interceptors non-trivial. I'd like to refer you to our [documentation page on this topic](https://github.com/castleproject/Core/blob/master/docs/dynamicproxy-async-interception.md), which goes into some details about some potential pitfalls and solutions. It also has some links to third-party resources that might help you out.
