### ISSUE TITLE
How to solve the dependence of Castle.core on System.Diagnostics.EventLog under netstandard2.1 framework

### ISSUE THREAD

**Issue by Splendour0207** [castleproject/Core#634]
While I was using Castle.Core in .Net Standard2.1,  I found that it depends on [System.Diagnostics.EventLog(v >= 4.70)]. 
![image](https://user-images.githubusercontent.com/18577195/199756149-47acaa3d-76c6-46bf-bd39-aa6ac889440b.png)
So,  I got System.Diagnostics.EventLog, But I found it did not support .Net Standard2.1 in any version.  I do not know how to solve it. thanks!
![image](https://user-images.githubusercontent.com/18577195/199758635-97c4b345-2d63-4527-9155-ae74dabd50ad.png)

**Comment by stakx** [comment]
You're looking at versioning information about the documentation page, not about the actual NuGet package. If you look at e.g. https://www.nuget.org/packages/System.Diagnostics.EventLog/4.7.0, you'll find that the NuGet package `System.Diagnostics.EventLog` _does_ support .NET Standard 2.1.
