### ISSUE TITLE
Update log4net integration to latest

### ISSUE THREAD

**Issue by kkozmic** [castleproject/Core#64]
I think it's time to upgrade to latest log4net version (with the new key).

This is a breaking change, as because of the new key, the log4net libraries can't use assembly redirect.

But, since our assembly retains the same key, people can assembly redirect between our new and old versions (as long as we don't change our API, which we most likely won't)

**Comment by jonorossi** [comment]
See #53.

**Comment by DaveMiscampbell** [comment]
Just to confirm, the decision on this is that it's not worth upgrading as most people aren't really using log4net anymore and are probably using other loggers such as SeriLog?

**Comment by jonorossi** [comment]
@DaveMiscampbell that was my observation not a decision. As I said in #53 I'm more than happy to discuss options since 1.2.11+ has an incompatible API change to 1.2.10.
