### ISSUE TITLE
it's very slow to create proxy

### ISSUE THREAD

**Issue by coader** [castleproject/Core#649]
`
var i = new EntityInterceptor();
var n = new ProxyGenerator().CreateClassProxy<TSource>(i);
`

it take 8 seconds when execute1000 times  in debug mode
how to improve it's performance?

**Comment by stakx** [comment]
Reuse a simple `ProxyGenerator` instead of recreating it in every iteration (as mentioned in our documentation).

**Comment by coader** [comment]
> Reuse a single `ProxyGenerator` instance, instead of recreating it in every iteration (as mentioned in our documentation).

got it, it works, tks
