### ISSUE TITLE
Endless loop when serializing a RemotableInvocation

### ISSUE THREAD

**Issue by ulrichb** [castleproject/Core#65]
```C#
var remotableInvocation = new RemotableInvocation(null);

var binaryFormatter = new BinaryFormatter();

// After running ~50 sec on my system Serialize() eventually throws a 
// SerializationException ("The internal array cannot expand to greater 
// than Int32.MaxValue elements"):
binaryFormatter.Serialize(new MemoryStream(), remotableInvocation);
```

The reason is https://github.com/castleproject/Core/blob/6b16fcdadad12b7c86d7fd1ebc45417efe935ec7/src/Castle.Core/DynamicProxy/Serialization/RemotableInvocation.cs#L123 (maybe a copy paste error happened in commit https://github.com/castleproject/Castle.DynamicProxy-READONLY/commit/3f6fd9249f94cf2886260888751226276944e40b). 

It seems that there are no automated tests for the serialization of a `RemotableInvocation ` instance.

**Comment by kkozmic** [comment]
I vaguely remember looking at this issue around the time when it was first logged in YouTrack. Can't recall the details but I ended up thinking it was more tricky than it looked at first glance. Now, if I only remembered why...

Anyway, would be nice to fix it somehow.

**Comment by jonorossi** [comment]
If I recall correctly the endless loop is from `RemotableInvocation.GetObjectData` [creating a `RemotableInvocation` and passing itself](https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Serialization/RemotableInvocation.cs#L122).

From my comment on Oct 26, 2014, I think the hard part was getting it to deserialize:

> however I'm not sure what to do for the constructor to deserialize because you need to get back to something implementing AbstractInvocation otherwise it is unusable.

I think we should just close this issue as won't fix because no one has an actual use case for it, and .NET Core won't support binary serialization (https://github.com/dotnet/corefx/issues/1347).

**Comment by kkozmic** [comment]
I'm ok with that, unless someone has a better suggestion

On Thu, 10 Sep 2015 at 18:02 Jonathon Rossi <notifications@github.com>
wrote:

> If I recall correctly the endless loop is from
> RemotableInvocation.GetObjectData creating a RemotableInvocation and
> passing itself
> <https://github.com/castleproject/Core/blob/master/src/Castle.Core/DynamicProxy/Serialization/RemotableInvocation.cs#L122>
> .
>
> From my comment on Oct 26, 2014, I think the hard part was getting it to
> deserialize:
>
> however I'm not sure what to do for the constructor to deserialize because
> you need to get back to something implementing AbstractInvocation otherwise
> it is unusable.
>
> I think we should just close this issue as won't fix because no one has an
> actual use case for it, and .NET Core won't support binary serialization (
> dotnet/corefx#1347 <https://github.com/dotnet/corefx/issues/1347>).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castleproject/Core/issues/65#issuecomment-139157113>.
>
-- 

sent from my phone
Krzysztof

**Comment by ulrichb** [comment]
Shouldn't we at least remove the (broken and untested) serializability of the concerned classes?

**Comment by jonorossi** [comment]
@ulrichb I avoided doing it right now because I've got outstanding .NET Core changes to come. However, we could delete just `RemotableInvocation` and remove the implementation of `ISerializable` in `AbstractInvocation`, that isn't likely to cause any conflicts.

**Comment by ulrichb** [comment]
:+1: I think this would be better than having an endless loop in the serialization code.

**Comment by jonorossi** [comment]
Removed in #110. Thanks.
