### ISSUE TITLE
Log4Net not listed in dependencies

### ISSUE THREAD

**Issue by brettshearer** [castleproject/Core#650]
In 5.0.0 release notes:

Upgrade log4net to v2.0.13 (@jonorossi, @stakx, @dschwartzni, https://github.com/castleproject/Core/pull/574, https://github.com/castleproject/Core/pull/605)

Yet log4net doesn't appear in dependencies on this page:
https://www.nuget.org/packages/Castle.Core

Here is the reference:
https://github.com/castleproject/Core/blob/master/src/Castle.Services.Logging.SerilogIntegration/Castle.Services.Logging.SerilogIntegration.csproj

**Comment by stakx** [comment]
Seems like you're looking at the wrong project and at the wrong package.

The Castle.Core&ndash;log4net integration project is here:  
https://github.com/castleproject/Core/blob/master/src/Castle.Services.Logging.log4netIntegration/Castle.Services.Logging.log4netIntegration.csproj

And the NuGet package is here:  
https://www.nuget.org/packages/Castle.Core-log4net

And voilà, the dependency is right where it should be.

**Comment by jonorossi** [comment]
@brettshearer The second link you provided is the project file for `Castle.Core-Serilog`, not really sure why you provided that, the log4net project and package is:

* https://github.com/castleproject/Core/blob/master/src/Castle.Services.Logging.log4netIntegration/Castle.Services.Logging.log4netIntegration.csproj
* https://www.nuget.org/packages/Castle.Core-log4net

**Comment by stakx** [comment]
Wow, almost identical answers with identical links at almost exactly the same time, @jonorossi. We must be quantum entangled or something.

**Comment by brettshearer** [comment]
excellent - thanks. I'm in a massive entanglement session and got this wrong.
