### ISSUE TITLE
.NET 9 compatibility: Signature of the body and declaration in a method implementation do not match

### ISSUE THREAD

**Issue by GC-Configit** [castleproject/Core#677]
Hi, 
I'm running my application using the dotnet 9 preview version. Previously at net 8, everything was working fine. Unfortunately, now I get the exception `Signature of the body and declaration in a method implementation do not match.` while using `CreateInterfaceProxyWithoutTarget`.  Did anyone else try to run `Castle. Proxies` with net9? I've just updated the target framework to `net9.0` and updated some base Microsoft packages.

**Comment by jonorossi** [comment]
@GC-Configit have you run the DynamicProxy unit tests on .NET 9 to see if that pinpoints a problem area or if its something not covered by the unit tests?

**Comment by stakx** [comment]
I've run our test suite on .NET 9 Preview: all tests are passing. So we would definitely need a minimally complete & verifiable repro.

**Comment by GC-Configit** [comment]
We have tried to replicate the issue using a fresh solution. But there everything was working fine. 

We got rid of the proxy in our project, but I'm afraid it could be an issue with our codebase, not the library. So I think we can close the issue. Thanks for help :)
