### ISSUE TITLE
ProxyGenerationOptions.AdditionalAttributes not part of cache key

### ISSUE THREAD

**Issue by ulrichb** [castleproject/Core#71]
The following test is red because the second `CreateClassProxyType()` returns *the same type* although the `AdditionalAttributes` differ.

The reason is that [`ProxyGenerationOptions.Equals()`](https://github.com/castleproject/Core/blob/5bb4c41297d38e4d35cf6d109fe8990746a977f3/src/Castle.Core/DynamicProxy/ProxyGenerationOptions.cs#L162) doesn't include `AdditionalAttributes`, which is important for the [cache look-up in `ClassProxyGenerator`](https://github.com/castleproject/Core/blob/5bb4c41297d38e4d35cf6d109fe8990746a977f3/src/Castle.Core/DynamicProxy/Generators/ClassProxyGenerator.cs#L44).

Isn't `AdditionalAttributes` also missing in the (de)serialization methods of `ProxyGenerationOptions`?

```c#
[TestFixture]
public class CustomAttributes
{
  [AttributeUsage (AttributeTargets.Class)]
  public class MyAttribute1 : Attribute { }

  [AttributeUsage (AttributeTargets.Class)]
  public class MyAttribute2 : Attribute { }

  public abstract class Foo  { }

  [Test]
  public void Test ()
  {
    var proxyBuilder = new DefaultProxyBuilder();

    var attribute1Ctor = typeof(MyAttribute1).GetConstructors().Single();
    var attribute2Ctor = typeof(MyAttribute2).GetConstructors().Single();

    var type1 = proxyBuilder.CreateClassProxyType(
        typeof (Foo),
        new Type[0],
        new ProxyGenerationOptions
        {
            AdditionalAttributes = { new CustomAttributeBuilder(attribute1Ctor, new object[0]) }
        });

    var type2 = proxyBuilder.CreateClassProxyType(
        typeof (Foo),
        new Type[0],
        new ProxyGenerationOptions {
            AdditionalAttributes = { new CustomAttributeBuilder(attribute2Ctor, new object[0]) }
        });

    Assert.AreNotSame(type1, type2);
  }
}
```

**Comment by jonorossi** [comment]
#77/#78 fix `AdditionalAttributes` missing from the caching. I'm not aware of anyone actually using the remoting features and I think there are more problems than just `AdditionalAttributes` missing for it to even work, so I'm going close this as resolved. Thanks.
