### ISSUE TITLE
auto-generate ending copyright year in NuGet packages

### ISSUE THREAD

**Issue by blairconrad** [castleproject/Core#75]
Back when I fixed castleproject/Windsor#57, I added a bit where the current year is put in as the "end" copyright year in the NuGet packages.
I hadn't done that when I fixed #49, and ~~it's been eating me up inside ever since~~ I think about it from time to time. Now that we have a new year, it's actually become relevant.

Any interest in me upgrading the Core "Pack" task so it does the same thing?

**Comment by jonorossi** [comment]
Sure, go for it.

**Comment by blairconrad** [comment]
Great. Pull request coming real soon now. In addition to merging, the [Core > Pack](http://builds.castleproject.org/admin/editBuild.html?id=buildType:Core_Pack) configuration will need to be updated to match [Core Blair > Pack](http://builds.castleproject.org/admin/editBuildRunners.html?id=buildType:CoreBlair_Pack) (which I'll remove after we're done):

1. Build Step 1 (Get NuGet Version):
    1. change **Step name** to "Get Build Variables" (optional, but matches Windsor's Pack)
    1. change **Script file** to `buildscripts\Get-NuGetVars.ps1`
1. Build Step 2 (NuGet Pack):
    1. add the following **Property**: `CurrentYear=%CurrentYear%`
1. Build Parameters:
   1. add a new **Configuration Parameter**:
        * Name: `CurrentYear`
        * Value: `2000` (really doesn't matter, I suppose)
        * Spec: `text description='Copyright Year' display='hidden' label='Copyright Year' regexp='20\d\d' validationMode='regex'`  
![image](https://cloud.githubusercontent.com/assets/3275797/5720592/38e4f98c-9af4-11e4-8e61-b18918cbcaf1.png)

(Sorry to make work for you. Too bad the build config can't just be merged.)

And I think that should just about do it. Thanks for indulging me.

**Comment by jonorossi** [comment]
I've merged the pull request. Do you mind just making the changes to the build configuration yourself. I've disabled the build agents so no builds will be running from the merge.

**Comment by blairconrad** [comment]
Happy to. Once I think I'm done, shall I re-enable the build agents?

**Comment by jonorossi** [comment]
Yep, let me know if you don't have permissions.

**Comment by blairconrad** [comment]
Re-enabled. All packages but Pack built.
Pack was showing one build queued, but no agents available because of the missing implicit requirement `%CurrentYear%. I rechecked my config, and it looked good. Then I looked at the [compatible agents](http://builds.castleproject.org/viewType.html?buildTypeId=Core_Pack&tab=compatibilityList) and saw castlebuild-windows. Reasoning that maybe the queued job was stuck because it was created _before_ I updated the configuration for Pack, I hit the build button on Pack. Worked like a charm.

I'm not sure what other test to do, besides committing something, so I'm going to remove the queued build and hope that everything's fine. I have a good feeling.

Thanks again.

**Comment by jonorossi** [comment]
Sounds about right, I'm happy for you to just remove the queued build, and we can close this.

**Comment by blairconrad** [comment]
Done and done. Removing "Blair Core" now. Thanks!

**Comment by blairconrad** [comment]
Closed via #76 and TeamCity configuration changes.

**Comment by jonorossi** [comment]
Thanks
