### ISSUE TITLE
Mono support for Castle Core

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#79]
Over the last month I've spent a little bit of time trying to get our build set up working well for Mono, so that I could look into #72 knowing any new unit tests would then be running on our CI server.

This issue follows on from a [thread on the mailing list](https://groups.google.com/d/topic/castle-project-devel/IXcREGqGr9A/discussion) which didn't yield any results.

So far I've:
* Fixed a bunch of small issues (e.g. b320a571bda86e82994362e3fd910ea55470d4de, 8cf8c3cd38521509f5ea073be30c5a3dd9dea3a7, e33c78b7ffd3127d8baa87d299380cfd9aee2a6b)
* Removed the really old Mono 2.6 and 2.8 configurations and replaced them with a Mono 3.10 for now (76545116f29754ca66d9ec0202519d3280efd660).
* Changed the way we run unit tests on Mono (423428918f776c4e44978d578d19a94afc53f995).
* Attempted to fix unit tests failing on Mono on Linux but not OSX with errors like "Missing method .ctor in assembly ..., type ExtensionAttribute" (86df41fefb7e93b0b7294a7479c78cd4ec73fb07, 3080c4c0c0ec1b84ed7e39abfebeaae3c7470217).

I'm now stuck with these strange missing constructor errors. It seems Mono on Linux isn't liking the NLog and Serilog assemblies. Following is the error message running unit tests on Mono 3.10 on the Ubuntu TeamCity agent:

    Missing method .ctor in assembly /home/teamcity/buildagent/work/16de7b8c88ab14af/lib/net45/NLog.dll, type System.Runtime.CompilerServices.ExtensionAttribute
    Can't find custom attr constructor image: /home/teamcity/buildagent/work/16de7b8c88ab14af/lib/net45/NLog.dll mtoken: 0x0a000018
(http://builds.castleproject.org/viewType.html?buildTypeId=Core_MasterMono310)

I've read mentions that this type of error is caused by the fact `ExtensionAttribute` moved assembly between .NET 4.0 and 4.5 via a `TypeForwardedTo`, but I'm trying to avoid building log4net, NLog and Serilog from source in our build.

I'd like if we can remove the MONO310 build configuration completely and compile using the NET45 one. The only reason I've kept it for now is so I could easily switch between using `lib/net40` and `lib/net45` binaries without affecting anything else. You'll [see that I've disabled](https://github.com/castleproject/Core/blob/master/src/Castle.Core/Castle.Core.csproj#L155) the `MONO` define by renaming it so all that conditional code is built on Mono.

**Comment by kkozmic** [comment]
Any update on that?

**Comment by jonorossi** [comment]
I haven't had a chance to get back to it, however [James has been making some progress](https://groups.google.com/forum/#!topic/castle-project-devel/3dk5lb_GOtw). I'll try to find some time to upgrade the TeamCity Linux agent to Mono 3.12.1 and give it another look.

**Comment by kkozmic** [comment]
Ok no worries

**Comment by jonorossi** [comment]
I've made a heap of progress on mono support. I've got everything building without `Castle.Core.dll` being conditionally compiled using our `NET45-Release` configuration, however `Castle.Core.Tests.dll` is conditionally compiled to handle slight differences and ignore failing and crashing unit tests for now.

The branch is [`mono-support`](https://github.com/castleproject/Core/tree/mono-support) and the builds are available at http://builds.castleproject.org/project.html?projectId=Core.

**Comment by jonorossi** [comment]
I reinstalled our Mono Linux build agent the other day which resolved the `Missing method .ctor in assembly` problems, I suspect the upgrade of Mono from 3.12 to 4.0.1 didn't quite work right last time.

I've still got some more work to do and then I'll post another update about what is left before is in a good state, but the build output now should be no worse than it was before.

**Comment by floydpink** [comment]
Great stuff, Jono. :+1: 

What is the development setup you're using for Mac/Linux? I am trying to use Xamarin/MonoDevelop, but since the project being built from the command-line build is different from the main project/solution, I have been seeing some differences in the build/test from within the IDE.

**Comment by jonorossi** [comment]
@floydpink just using Atom+Terminal.app on Mac and Vim on Linux. No OmniSharp, but I might look at that later. I also tried Xamarin Studio a few months ago and it didn't handle the conditional references and stuff that we've got in the csproj files so I gave up with it. Will probably need to look at it again, what differences are you seeing?

**Comment by floydpink** [comment]
When trying to build `NET45-Debug` or `NET45-Release` configurations from within Xamarin on Mac after opening `Castle.Core.sln`, these things have to be done for the build to be successful:

1. Add the missing project reference to `Castle.Services.Logging.log4netIntegration` to `Castle.Core.Tests` project
2. Disable the compiler setting of `Treat warnings as errors` for the `Castle.Core.Tests` project

But even after the solution starts building, the Unit Tests pad/pane within Xamarin does not show any of the tests within the solution.

All of these could be Xamarin Studio nuances - I haven't spent enough time yet on these.

**Comment by jonorossi** [comment]
@floydpink I've logged a separate issue to sort out Xamarin Studio (#93)

I've also logged #94 to track fixing the remaining unit tests, feel free to help with any of them.

**Comment by jonorossi** [comment]
I merged my `mono-support` branches a year ago and things are in a pretty good state, however there are still some known issues. I'm closing this issue as there isn't anymore to do at an overall level.
