### ISSUE TITLE
Support method level interception

### ISSUE THREAD

**Issue by YuvalItzchakov** [castleproject/Core#80]
I've been searching around to see if it is possible to use interceptors for method level interception, and came across the following from the docs:

"The InterceptorAttribute is defined in a way that allows you to put it not only on classes, but on any other target where custom attribute is allowed, like interface or a method. However Windsor will ignore the attribute unless it's on component's implementation class. This permissive behavior was introduced to allow people to add support for other targets by building custom extensions."

I think adding a fine grained control for interception at the method level would be a great thing for general purpose aspects such as logging, performance counters, etc.

**Comment by jonorossi** [comment]
Could you provide an example of what you'd like to do, maybe a code snippet/pseudocode.

My understanding of your request is currently what you do today with Castle DynamicProxy and/or Castle Windsor. Take a look at the [DynamicProxy Introduction](http://docs.castleproject.org/Tools.DynamicProxy-Introduction.ashx).

**Comment by Yuvalos** [comment]
Right, so what im trying to do is create an interceptor which will be able to intercept at the method level, for example. Lets say i have class Foo with two methods:

    public class Foo : IFoo
    {
        [Log]
        public void Fooable()
        {
            Console.WriteLine("In Fooable");
        }

        public void Barable()
        {
            Console.WriteLine("In Fooable");
        }
    }

I want to intercept only calls on Foo that have a LogAttribute. I don't want the entire class to be intercepted, but only specific methods.

**Comment by kkozmic** [comment]
A `IProxyGenerationHook`can help you do that

**Comment by kkozmic** [comment]
Can we close this issue? It looks like it's been resolved...

**Comment by jonorossi** [comment]
Let us know if `IProxyGenerationHook` doesn't fulfil your requirements, closing.
