### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in DynamicProxyGenAssembly2

### ISSUE THREAD

**Issue by HamedFathi** [castleproject/Core#84]
I want to write an Attribute with Castle DynamicProxy Interceptor (**like OnMethodBoundaryAspect  in PostShart) with handling Exceptions** so
I wrote something like this :

### :: STEP 1 ::

I wrote a simple InterceptorAttribute class : 

    [AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
    public class InterceptorAttribute : System.Attribute
    {

        public Type Interceptor { get; set; }

        public string Methods { get; set; }

        public InterceptorAttribute(Type interceptor)
        {

            this.Interceptor = interceptor;
        }
    }

### :: STEP 2 ::

I wrote MethodBoundaryAspect class 

    public abstract class MethodBoundaryAspect : IInterceptor
    {
        public void Intercept(IInvocation invocation)
        {
            try
            {
                var method = invocation.Method.Name;
                if (this.Methods != null)
                {
                    if (!this.Methods.Contains(method))
                    {
                        invocation.Proceed();
                        return;
                    }
                }
                ExecuteBefore(invocation);
                invocation.Proceed();
                ExecuteAfter(invocation);
            }
            catch (Exception ex)
            {

                HandleException(invocation, ex);
            }
        }

        public string[] Methods { get; set; }

        public MethodBoundaryAspect(string[] methods = null)
        {
            this.Methods = methods;
        }

        protected abstract void ExecuteAfter(IInvocation invocation);
        protected abstract void ExecuteBefore(IInvocation invocation);
        protected abstract void HandleException(IInvocation invocation, Exception ex);
    }

### :: STEP 3 ::

I wrote a Helper class for registration 

    public static class Interceptor
    {
        public static TClass Register<TClass>()
            where TClass : class,new()
        {
            var interceptors = typeof(Calculator).GetCustomAttributes(typeof(InterceptorAttribute), false);

            var customInterceptor = ((InterceptorAttribute)interceptors[0]);
            string[] methods = customInterceptor.Methods == null ? null : customInterceptor.Methods.Split(',');
            ConstructorInfo ctorCustom = customInterceptor.Interceptor.GetConstructor(new[] { typeof(string[]) });
            var instanceCustom = (IInterceptor)ctorCustom.Invoke(new object[] { methods });

            ProxyGenerator generator = new ProxyGenerator();
            var tc = generator.CreateClassProxy<TClass>(instanceCustom);
            return tc;
        }

        public static TClass Register<TClass>(ProxyGenerationOptions options, params IInterceptor[] interceptors)
            where TClass : class,new()
        {
            ProxyGenerator generator = new ProxyGenerator();
            var tc = generator.CreateClassProxy<TClass>(options, interceptors);
            return tc;
        }
    }

### :: STEP 4 ::

I wrote simple Interceptor for my class

    public class CalculatorInterceptor : MethodBoundaryAspect
    {
		public CalculatorInterceptor( string[] methods )
			: base( methods ) {

		}
		protected override void ExecuteBefore( Castle.DynamicProxy.IInvocation invocation ) {
			Console.WriteLine( "Start" );
		}

		protected override void ExecuteAfter( Castle.DynamicProxy.IInvocation invocation ) {
			Console.WriteLine( "End" );
		}

        protected override void HandleException(Castle.DynamicProxy.IInvocation invocation, Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
    }

### :: STEP 5 ::

I wrote a simple Claculator class and bound Interceptor to "Div" method of it not for all

    [Interceptor( typeof( CalculatorInterceptor ) , Methods="Div" )]
	public class Calculator {
		public virtual int Add( int a , int b ) {
			var c = a + b;
			Console.WriteLine( c );
			return c;
		}

		public virtual int Sub( int a , int b ) {
			var c = a - b;
			Console.WriteLine( c );
			return c;
		}

		public virtual int Mult( int a , int b ) {
			var c = a * b;
			Console.WriteLine( c );
			return c;
		}

		public virtual int Div( int a , int b ) {
			var c = a / b;
			Console.WriteLine( c );
			return c;
		}

	}

### :: STEP 6 ::

as final step , I want to use these classes now

    class Program
    {
        static void Main(string[] args)
        {
            var calc = Interceptor.Register<Calculator>();

            //Error Here****************************************************************
            calc.Div(11, 0);
            //Error Here****************************************************************

            Console.ReadKey();
        }
    }

so when I run it :

first I can catch correct exception , It is my goal  :D **(with HandleException() method)**

    Attempted to divide by zero.

but immediately after it DynamicProxy show this error :(  **(I want to skip any throwing exception only catch it with my HandleException() method like Postsharp that I can Continue after Exceptions)**

*THIS ERROR FAIL MY GOALS :(*

    An unhandled exception of type 'System.NullReferenceException' occurred in DynamicProxyGenAssembly2

    Additional information: Object reference not set to an instance of an object.

       at Castle.Proxies.CalculatorProxy.Div(Int32 a, Int32 b)
       at ConsoleApplication1.Program.Main(String[] args) in c:\...\ConsoleApplication1\ConsoleApplication1\Program.cs:line 29
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()

Seams this error from Castle.DynamicProxy 
Can anyone check it ?

I uploaded a sample in my OneDrive with above details and error
[Download My Sample](http://1drv.ms/1zDAwI0)

**Comment by Cinchoo** [comment]
Does anyone have fix for this? I'm facing similar issue with my project. Appreciate any help.

**Comment by jonorossi** [comment]
@Cinchoo this issue was closed over 2 years ago. If you are running into a `NullReferenceException` inside DynamicProxy, please create a new issue and include runnable code that reproduces your scenario.
