### ISSUE TITLE
AttributeUtil support for reflection only context

### ISSUE THREAD

**Issue by cherrydev** [castleproject/Core#86]
AttributeUtil methods like .HasAttribute is useful for trying to determine if you want to REALLY load an assembly into the execution context when it's in the reflection only context, but you can't call GetCustomAttributes on a member of an reflection only assembly.
The workaround, at least for HasAttribute (which only determines if the member has the attribute but doesn't need to actually materialize it) is to use CustomAttributeData.GetCustomAttributes().
Obviously this won't work for any usage that requires the instance of the attribute itself.

**Comment by kkozmic-seek** [comment]
where would that be useful for what we do?

**Comment by cherrydev** [comment]
Okay, sure.

Say you have some sort of plugin architecture for your software where you might be discovering plugin assemblies at runtime, but you don't want to load them into the execution context unless you really need to.  So, you provisionally load your assemblies into the reflection only context and want to determine if one of the classes in the assembly contains an attribute that's of interest (for example, it indicates that a class provides a service and therefore you want to load it).  If you were to use .HasAttribute with a class from a reflection only assembly, you'd get an exception.  If .HasAttribute instead used CustomAttributeData.GetCustomAttributes() it would work as expected.
It's at most a small enhancement, but this is something that I actually came across personally, learned about CustomAttributeData and decided to share that knowledge back here in case it might be useful.

**Comment by kkozmic-seek** [comment]
I see. Thanks.

The aim of classes in the `Castle.*.Internal` namespaces (like `ReflectionUtil`) was to provide support functionality for the inner workings of Castle, and as such, not really meant for public consumption. The classes are public but I think it's unlikely we would make changes to them unless the Castle framework internally requires them.

Having said that, it's all open source so as long as you comply with the license you can grab the code and take it any direction you want :)
