### ISSUE TITLE
Fix problems using Xamarin Studio

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#93]
> When trying to build NET45-Debug or NET45-Release configurations from within Xamarin on Mac after opening Castle.Core.sln, these things have to be done for the build to be successful:
> 
> Add the missing project reference to Castle.Services.Logging.log4netIntegration to Castle.Core.Tests project
> Disable the compiler setting of Treat warnings as errors for the Castle.Core.Tests project
> But even after the solution starts building, the Unit Tests pad/pane within Xamarin does not show any of the tests within the solution.
> 
> All of these could be Xamarin Studio nuances - I haven't spent enough time yet on these.
(@floydpink)

**Comment by jonorossi** [comment]
@floydpink any interest in looking at Xamarin Studio anymore?

**Comment by floydpink** [comment]
@jonorossi The project where I ran into the DP issues on has been dormant for quite a while because I haven't been getting any time. If I do find time to figure out something useful I would definitely post here

**Comment by jonorossi** [comment]
@floydpink thanks. I'll close the issue for now until we've got some more concrete info on what is needed since there isn't much demand for it, feel free to reopen it when you get some time for that project.
