### ISSUE TITLE
Mono: Fix remaining ignored unit tests

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#94]
See parent issue: #79

These are the remaining ~~136~~ 117 (1391 - 1274) unit tests that I've ignored. Feel free to send in a PR for any of them on the ~~`mono-support`~~ `master` branch.

I've permanently ignored a few unit tests using the `[Platform(Exclude = "mono", Reason = "...")]` syntax, and am using `#if __MonoCS__  [Ignore("...")]  #endif` for those still to fix.
## DynamicProxy
- ~~`Assertion at sgen-alloc.c:460, condition '*p == NULL' not met`~~
  - ~~Fixed in https://bugzilla.xamarin.com/show_bug.cgi?id=28182~~
  - ~~It isn't in the [4.0.2 release notes](http://www.mono-project.com/docs/about-mono/releases/4.0.2/) however it is fixed in 4.0.2 in https://github.com/mono/mono/commit/ef16e5a45c0e8fa6d9305aaa885c53ad008f10b2~~
- ~~`System.Type[] doesn't implement interface Castle.DynamicProxy.IInvocation`~~
  - ~~Fixed in 4.0.2, caused by the same defect as the `Assertion at sgen-alloc.c:460, condition '*p == NULL' not met` runtime crash~~
- ~~`Assertion at reflection.c:2745, condition 'field' not met`~~
  - #72
- `System.InvalidCastException : Cannot cast from source type to destination type.`
  - src/Castle.Core.Tests/GenericClassProxyTestCase.cs
- `System.ArgumentException : Constant does not match the defined type.`
  - src/Castle.Core.Tests/DynamicProxy.Tests/ClassProxyWithDefaultValuesTestCase.cs
  - src/Castle.Core.Tests/DynamicProxy.Tests/ClassProxyWithMethodsWithOptionalParametersTestCase.cs
  - src/Castle.Core.Tests/DynamicProxy.Tests/InterfaceProxyWithMethodsWithOptionalParametersTestCase.cs
- ~~`NUnit.Framework.AssertionException was expected`~~
  - ~~src/Castle.Core.Tests/BaseTestCaseTestCase.cs... was caused because peverify isn't available on mono, permanently disabled the unit test~~
- `Expected: Castle.DynamicProxy.Generators.GeneratorException, But was: System.ArgumentNullException`
  - src/Castle.Core.Tests/BasicClassProxyTestCase.cs
- `Expected: xxxx.dll  But was:  /home/teamcity/buildagent/work/...`
  - src/Castle.Core.Tests/ModuleScopeTestCase.cs
- `Expected: True  But was:  False`
  - src/Castle.Core.Tests/PersistentProxyBuilderTestCase.cs -> PersistentProxyBuilder_SavesSignedFile
  - src/Castle.Core.Tests/BaseTestCaseTestCase.cs -> TearDown_SavesAssembly_IfProxyGenerated
- `Expected: True  But was: False`
  - src/Castle.Core.Tests/ClassWithAttributesTestCase.cs -> EnsureProxyHasAttributesOnGenericArgument
- `Expected: False  But was: True`
  - src/Castle.Core.Tests/DynamicProxy.Tests/ClassProxyWithDefaultValuesTestCase.cs -> MethodParameterWithDefaultValue_DefaultValueNullIsSetOnProxiedMethodAsWell
## DictionaryAdapter
- `System.NullReferenceException : Object reference not set to an instance of an object`
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/Behaviors/ConflictBehaviorTestCase.cs
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/Behaviors/XPathBehaviorTestCase.cs
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlAdapterAcceptanceTestCase.cs
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlApis/SysXmlCursorTestCase.cs
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlApis/XPathMutableCursorTestCase.cs
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlApis/XPathReadableCursorTestCase.cs
- `System.Xml.XPath.XPathException : variable p:v not found`
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/Behaviors/XPathBehaviorTestCase.cs
- `String lengths are both 7. Strings differ at index 0.  Expected: 'correct'  But was: 'wrong B'`
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/Behaviors/XPathBehaviorTestCase.cs
- `Expected: urn:a:T  But was: T`
  - src/Castle.Core.Tests/Components.DictionaryAdapter.Tests/Xml/XmlApis/XmlNodeTestCase.cs
- `Expected: 0  But was: 1`
  - src/Castle.Core.Tests/Core.Tests/Internal/WeakKeyDictionaryTestCase.cs

**Comment by RalphBariz** [comment]
wanted to take a look today, but the mono branch is gone :(

**Comment by floydpink** [comment]
@RalphBariz - #95 merged the `mono-support` branch into master, so latest on master should give all these failing unit tests when run from Mono

**Comment by jonorossi** [comment]
Moving this issue out of v4.0, there are still a bunch of failing unit tests when running on Mono because of differences in runtime behaviour or BCL implementation.

**Comment by jonorossi** [comment]
This issue is now out of date after the work @stakx has done in #351, the Mono team have fixed some with more recent builds. There are very few unit tests now ignored on Mono, and just about every one of those that are ignored have a Mono issue referenced.

To work on this project with Mono you should be running at least 5.10.1, however older versions as mentioned in the readme are good if you just want to use the library.
