### ISSUE TITLE
SL5 in nuget package's SL4 folder

### ISSUE THREAD

**Issue by scott-xu** [castleproject/Core#97]
// C:\Users\Scott\Documents\GitHub\ninject.mockingkernel\packages\Moq.4.2.1506.2515\lib\***sl4\Moq.Silverlight.dll***
// Moq.Silverlight, Version=4.2.1506.2515, Culture=neutral, PublicKeyToken=69f491c39445e920

// Architecture: AnyCPU (64-bit preferred)
// Runtime: .NET 4.0

using System;
using System.Diagnostics;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
[assembly: AssemblyVersion("4.2.1506.2515")]
[assembly: CLSCompliant(true)]
[assembly: Debuggable]
[assembly: AssemblyCompany("Clarius Consulting, Manas Technology Solutions, InSTEDD")]
[assembly: AssemblyFileVersion("4.2.1506.2515")]
[assembly: AssemblyProduct("Moq")]
[assembly: AssemblyTitle("Moq")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: CompilationRelaxations(8)]
[assembly: InternalsVisibleTo("Moq.Silverlight.Tests, PublicKey=00240000048000009400000006020000002400005253413100040000010001009f7a95086500f8f66d892174803850fed9c22225c2ccfff21f39c8af8abfa5415b1664efd0d8e0a6f7f2513b1c11659bd84723dc7900c3d481b833a73a2bcf1ed94c16c4be64d54352c86956c89930444e9ac15124d3693e3f029818e8410f167399d6b995324b635e95353ba97bfab856abbaeb9b40c9b160070c6325e22ddc")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2,PublicKey=0024000004800000940000000602000000240000525341310004000001000100c547cac37abd99c8db225ef2f6c8a3602f3b3606cc9891605d02baa56104f4cfc0734aa39b93bf7852f7d9266654753cc297e7d2edfe0bac1cdcf9f717241550e0a7b191195b7667bb4f64bcb8e2121380fd1d9d46ad2d92d2d15605093924cceaf74c4861eff62abf69b9291ed0a340e113be11e6a7d3113e92484cf7045cc7")]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: ComVisible(false)]
***[assembly: TargetFramework("Silverlight,Version=v5.0", FrameworkDisplayName = "Silverlight 4")]***

**Comment by jonorossi** [comment]
@scott-xu this is the Castle Core repository, you'll need to log an issue in the [Moq](https://github.com/Moq/moq4) repository, closing.

**Comment by scott-xu** [comment]
Opps.. sorry for that.
