### ISSUE TITLE
64bit Castle Dynamic Proxy bad performance

### ISSUE THREAD

**Issue by informatorius** [castleproject/Core#99]
Since I build all targets in 64bit instead of 32bit, the unit test duration has doubled because Moq is 50% slower in 64bit. Moq is using Castle Dynamic Proxy. 
So can you confirm this problem? 
Any ideas how to enhance Castle Dynamic Proxy performance in 64bit?

**Comment by kkozmic** [comment]
Hi there,

Have you verified your observations? Let's have a look through your profiler  results for x86 and x64 to compare where the difference lies

**Comment by informatorius** [comment]
I also opened an issue at Moq but want to see if it is a known problem in Castle Dynamic Proxy?
https://github.com/Moq/moq4/issues/188
I will do performance traces when I find time to do, has anyone else already did that?

**Comment by informatorius** [comment]
I found .net 4.6 RyuJIT improves performance by 20%

**Comment by informatorius** [comment]
I did some performance profiling for a sample unittest with x86 and x64.
As you can see in the attached screenshots x64 takes two times x86.
Is this from CastleProxy or Moq?
![profile-86](https://cloud.githubusercontent.com/assets/6989214/9604744/9711f2fa-50b9-11e5-87e8-f48f2a9688c9.PNG)
![profile-64](https://cloud.githubusercontent.com/assets/6989214/9604747/9ad77d9c-50b9-11e5-896f-d23412176fd7.PNG)

**Comment by kkozmic** [comment]
I don't see any Castle code in that stack trace

On Tue, 1 Sep 2015 at 22:56 informatorius <notifications@github.com> wrote:

> I did some performance profiling for a sample unittest with x86 and x64.
> As you can see in the attached screenshots x64 takes two times x86.
> Is this from CastleProxy or Moq?
> [image: profile-86]
> <https://cloud.githubusercontent.com/assets/6989214/9604744/9711f2fa-50b9-11e5-87e8-f48f2a9688c9.PNG>
> [image: profile-64]
> <https://cloud.githubusercontent.com/assets/6989214/9604747/9ad77d9c-50b9-11e5-896f-d23412176fd7.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castleproject/Core/issues/99#issuecomment-136708090>.
>
-- 

sent from my phone
Krzysztof

**Comment by jonorossi** [comment]
@informatorius as Krzysztof said `Castle.*` namespaces don't show up in the snippet of the call stack you've shown. Is that the whole trace or is that the hot paths? Why do you have a call to `MessageBox.Show`? Could you please provide the code you are using to benchmark this.

**Comment by informatorius** [comment]
This is the whole trace if I did it right. The MessageBox.Show was just a trigger for me take the profiler snapshot. So if you don't see Castle here then it is a Moq only problem. I believe it is the LambdaCompiler.Compile from .Net which is slower in 64bit

My TestCode defines an Interface with 40 methods and creates an InterfaceMock using Moq.
Then for each method a Moq Setup is called in DoFurtherSetups.
The MessageBox.Show which holds until closed are my triggers for Profiler attach and capture.

        [TestMethod]
        public void TestMethod5()
        {
            MessageBox.Show("Attach");
            var interfaceMock = new InterfaceMock();
            interfaceMock.DoFurtherSetups();
            MessageBox.Show("Capture");
        }

**Comment by kkozmic** [comment]
That make sense. Feel free to close this issue unless there's more

On Wed, 2 Sep 2015 at 18:45 informatorius <notifications@github.com> wrote:

> This is the whole trace if I did it right. The MessageBox.Show was just a
> trigger for me take the profiler snapshot. So if you don't see Castle here
> then it is a Moq only problem. I believe it is the LambdaCompiler.Compile
> from .Net which is slower in 64bit
>
> My TestCode defines an Interface with 40 methods and creates an
> InterfaceMock using Moq.
> Then for each method a Moq Setup is called in DoFurtherSetups.
> The MessageBox.Show which holds until closed are my triggers for Profiler
> attach and capture.
>
>     [TestMethod]
>     public void TestMethod5()
>     {
>         MessageBox.Show("Attach");
>         var interfaceMock = new InterfaceMock();
>         interfaceMock.DoFurtherSetups();
>         MessageBox.Show("Capture");
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castleproject/Core/issues/99#issuecomment-136979793>.
>
-- 

sent from my phone
Krzysztof
